import xlsx from "xlsx";

// Distances are straight-line (great-circle) approximations from Boston, MA,
// for quick sorting/reference only — not driving distance.
const rows = [
  {
    Company: "ASM (ASM International)",
    "Role Title": "Manufacturing Engineering Intern",
    Discipline: "Manufacturing Engineering",
    Season: "Spring 2027 (Jan/Feb–Apr/May)",
    Location: "Greater Phoenix, AZ",
    "Distance from Boston, MA (mi, approx.)": 2300,
    Pay: "Not stated on posting",
    "Application Link": "https://www.asm.com/open-vacancies/manufacturing-engineering-intern-spring-2027-4830098101?gh_jid=4830098101",
    "Link Verified": "Yes — fetched directly, page live, Apply button present",
    Notes: "12 weeks, full-time, on-site. Enrolled full-time student required.",
  },
  {
    Company: "ASM (ASM International)",
    "Role Title": "Mechanical Engineering Intern",
    Discipline: "Mechanical Engineering",
    Season: "Spring 2027 (Jan/Feb–Apr/May)",
    Location: "Greater Phoenix, AZ",
    "Distance from Boston, MA (mi, approx.)": 2300,
    Pay: "Not stated on posting",
    "Application Link": "https://www.asm.com/open-vacancies/mechanical-engineering-intern-spring-2027-4830929101?gh_jid=4830929101",
    "Link Verified": "Yes — fetched directly, page live, Apply button present",
    Notes: "12 weeks, full-time, on-site. Enrolled full-time student required.",
  },
  {
    Company: "Varda Space Industries",
    "Role Title": "Manufacturing Engineering Internship",
    Discipline: "Manufacturing Engineering",
    Season: "Spring 2027 (Jan–May)",
    Location: "El Segundo, CA",
    "Distance from Boston, MA (mi, approx.)": 2600,
    Pay: "Not stated on posting",
    "Application Link": "https://job-boards.greenhouse.io/vardaspace/jobs/7824767003",
    "Link Verified": "Yes — fetched directly, page live, Apply button present",
    Notes: "Full-time, on-site. Must be enrolled undergrad/grad.",
  },
  {
    Company: "Formlabs",
    "Role Title": "Mechanical Engineering Intern",
    Discipline: "Mechanical Engineering",
    Season: "Winter/Spring 2027 (Jan–Apr)",
    Location: "Somerville, MA",
    "Distance from Boston, MA (mi, approx.)": 3,
    Pay: "Not stated on posting",
    "Application Link": "https://careers.formlabs.com/job/8130829/apply/?gh_jid=8130829&gh_src=lrhd6k1",
    "Link Verified": "Yes — fetched directly, page live",
    Notes: "Right in the Boston metro. Portfolio of prior engineering work requested.",
  },
  {
    Company: "Blue Origin",
    "Role Title": "Spring 2027 Aerospace Systems Engineering Intern – Graduate",
    Discipline: "Aerospace / Systems Engineering",
    Season: "Spring 2027 (Jan–Apr, ~15 wks)",
    Location: "Greater Seattle Area, WA",
    "Distance from Boston, MA (mi, approx.)": 2490,
    Pay: "Not stated on posting",
    "Application Link": "https://blueorigin.wd5.myworkdayjobs.com/BlueOrigin/job/Greater-Seattle-Area/Spring-2027-Aerospace-Systems-Engineering-Intern---Graduate_R66202/apply",
    "Link Verified": "Partial — official Blue Origin/Workday domain, title confirms season via direct search, but the page is JS-rendered and blocked automated fetch (403/empty). Open a browser to confirm before applying.",
    Notes: "US citizen/national/permanent resident required (ITAR).",
  },
  {
    Company: "Blue Origin",
    "Role Title": "Spring 2027 Aerospace Systems Engineering Internship – Undergraduate",
    Discipline: "Aerospace / Systems Engineering",
    Season: "Spring 2027 (Jan–Apr, ~15 wks)",
    Location: "Greater Seattle Area, WA",
    "Distance from Boston, MA (mi, approx.)": 2490,
    Pay: "Not stated on posting",
    "Application Link": "https://blueorigin.wd5.myworkdayjobs.com/BlueOrigin/job/Greater-Seattle-Area/Spring-2027-Aerospace-Systems-Engineering-Internship----Undergraduate_R66207/apply",
    "Link Verified": "Partial — same as above (Workday page blocked automated fetch). Verify live in-browser before applying.",
    Notes: "US citizen/national/permanent resident required (ITAR). Sophomore standing+.",
  },
  {
    Company: "Blue Origin",
    "Role Title": "Spring 2027 Structural & Mechanical Engineering Internship – Undergraduate",
    Discipline: "Structural / Mechanical Engineering",
    Season: "Spring 2027",
    Location: "Not specified on posting",
    "Distance from Boston, MA (mi, approx.)": null,
    Pay: "Not stated on posting",
    "Application Link": "https://blueorigin.wd5.myworkdayjobs.com/en-US/BlueOrigin/job/Spring-2027-Structural---Mechanical-Engineering-Internship---Undergraduate_R66356",
    "Link Verified": "Partial — official Workday domain, blocked automated fetch. Verify live in-browser before applying.",
    Notes: "US citizen/national/permanent resident required (ITAR).",
  },
  {
    Company: "Blue Origin",
    "Role Title": "Spring 2027 Structural & Mechanical Systems Engineering Internship – Graduate",
    Discipline: "Structural / Mechanical Systems Engineering",
    Season: "Spring 2027 (~15 wks)",
    Location: "Los Angeles, CA",
    "Distance from Boston, MA (mi, approx.)": 2600,
    Pay: "Not stated on posting",
    "Application Link": "https://www.ziprecruiter.com/c/Blue-Origin/Job/Spring-2027-Structural-&-Mechanical-Systems-Engineering-Internship-Graduate/-in-Los-Angeles,CA?jid=67aec7854122d860",
    "Link Verified": "Partial — this is a ZipRecruiter mirror of the Blue Origin listing (couldn't locate the direct Workday URL). Confirm on blueorigin.com/careers before applying.",
    Notes: "Grad student, US citizen/national/permanent resident required (ITAR).",
  },
  {
    Company: "Blue Origin",
    "Role Title": "Spring 2027 Engineering Intern – Undergraduate",
    Discipline: "General Engineering (unspecified sub-discipline)",
    Season: "Spring 2027",
    Location: "Not specified on posting",
    "Distance from Boston, MA (mi, approx.)": null,
    Pay: "Not stated on posting",
    "Application Link": "https://blueorigin.wd5.myworkdayjobs.com/en-US/BlueOrigin/job/Spring-2027--Engineering-Intern---Undergraduate_R69064",
    "Link Verified": "Partial — official Workday domain, blocked automated fetch. Verify live in-browser before applying.",
    Notes: "US citizen/national/permanent resident required (ITAR).",
  },
  {
    Company: "Tesla",
    "Role Title": "Internship, Manufacturing Engineering, Optimus",
    Discipline: "Manufacturing Engineering",
    Season: "Winter/Spring 2027 (Jan–May)",
    Location: "Fremont, CA",
    "Distance from Boston, MA (mi, approx.)": 2700,
    Pay: "$20–$50/hr (Tesla's general posted internship pay band; not role-specific)",
    "Application Link": "https://www.tesla.com/careers/search/job/internship-manufacturing-engineering-optimus-winter-spring-2027-279034",
    "Link Verified": "Partial — official tesla.com domain, blocked automated fetch (403, bot protection). Verify live in-browser before applying.",
    Notes: "Min. 12 weeks, full-time, on-site.",
  },
  {
    Company: "Tesla",
    "Role Title": "Internship, Industrial Engineer, Manufacturing",
    Discipline: "Industrial Engineering",
    Season: "Winter/Spring 2027 (Jan–May)",
    Location: "Fremont, CA",
    "Distance from Boston, MA (mi, approx.)": 2700,
    Pay: "$20–$50/hr (Tesla's general posted internship pay band; not role-specific)",
    "Application Link": "https://www.tesla.com/careers/job/246725",
    "Link Verified": "Partial — official tesla.com domain, blocked automated fetch (403, bot protection). Verify live in-browser before applying.",
    Notes: "Min. 12 weeks, full-time, on-site.",
  },
  {
    Company: "Hendrick Motorsports",
    "Role Title": "Design Engineering Intern",
    Discipline: "Mechanical / Automotive Design Engineering",
    Season: "Spring/Summer 2027 (6–9 month assignment starting spring)",
    Location: "Charlotte, NC",
    "Distance from Boston, MA (mi, approx.)": 845,
    Pay: "Not stated on posting",
    "Application Link": "https://hendrick.wd5.myworkdayjobs.com/en-US/HMSCareers/job/Design-Engineering-Intern--Spring-Summer-2027-_R-80377",
    "Link Verified": "Partial — official Workday domain, blocked automated fetch. Verify live in-browser before applying.",
    Notes: "NASCAR team — structural/CAD design internship. Min GPA 2.8, 30+ semester hrs completed.",
  },
  {
    Company: "General Dynamics Mission Systems",
    "Role Title": "Infrastructure Engineer Co-op",
    Discipline: "Systems / Infrastructure Engineering",
    Season: "Fall 2026 or Spring 2027",
    Location: "Pittsfield, MA",
    "Distance from Boston, MA (mi, approx.)": 135,
    Pay: "Not stated on posting",
    "Application Link": "https://www.gd.com/careers/infrastructure-engineer-co-op-fall-2026-or-spring-2027-pittsfield-ma-us-2026-72403-gdms-opportunity",
    "Link Verified": "Partial — official gd.com domain, blocked automated fetch (403). Verify live in-browser before applying.",
    Notes: "Closest option to Boston besides Formlabs. Likely requires US citizenship (ITAR/clearance).",
  },
  {
    Company: "Boeing (South Carolina)",
    "Role Title": "2026 Specialty Program – BSC Co-op – Engineering Internship Program (Materials & Process Eng, Industrial Eng)",
    Discipline: "Materials/Process Engineering, Industrial Engineering",
    Season: "Fall 2026–Spring 2027 (6-month co-op)",
    Location: "North Charleston, SC (Boeing SC site)",
    "Distance from Boston, MA (mi, approx.)": 850,
    Pay: "Not stated on posting",
    "Application Link": "https://boeing.wd1.myworkdayjobs.com/en-US/INTERN/job/XMLNAME-2026-Specialty-Program---BSC-Co-op---Engineering-Internship-Program_JR2026491626",
    "Link Verified": "Partial — official Boeing/Workday domain, title/search snippet confirms Fall 2026–Spring 2027 span, but page is JS-rendered and blocked automated fetch. Verify live in-browser before applying.",
    Notes: "6-month co-op spanning into Spring 2027.",
  },
  {
    Company: "Boeing",
    "Role Title": "Drexel Internship Fall Co-op 2026 – Engineering (Software, Industrial, Manufacturing, Reliability/Maintainability, Systems, Mechanical Systems, Structures, Wire Install/Design)",
    Discipline: "Systems / Mechanical Systems / Structures / Manufacturing Engineering",
    Season: "Fall 2026–Spring 2027 (6-month co-op)",
    Location: "Not specified on posting (Drexel University co-op partnership — site varies by team)",
    "Distance from Boston, MA (mi, approx.)": null,
    Pay: "Not stated on posting",
    "Application Link": "https://boeing.wd1.myworkdayjobs.com/en-US/INTERN/job/Drexel-Internship-Fall-Co-op-2026---Engineering_JR2026515142",
    "Link Verified": "Partial — official Boeing/Workday domain, title/search snippet confirms Fall 2026–Spring 2027 span, but page is JS-rendered and blocked automated fetch. Verify live in-browser before applying.",
    Notes: "Restricted to Drexel University co-op program students — check eligibility before applying.",
  },
  {
    Company: "John Deere",
    "Role Title": "Part-Time Student – Factory Engineering",
    Discipline: "Manufacturing / Factory Engineering",
    Season: "Year-round part-time during school year (covers Winter 2026 & Spring 2027)",
    Location: "East Moline, IL",
    "Distance from Boston, MA (mi, approx.)": 980,
    Pay: "Not stated on posting",
    "Application Link": "https://careers.deere.com/careers/job/137468659226-part-time-student-factory-engineering-east-moline-il-east-moline-illinois-united-states?domain=johndeere.com",
    "Link Verified": "Partial — official careers.deere.com domain, page structure confirmed real but automated fetch couldn't render full listing text. Verify live in-browser before applying.",
    Notes: "16–20 hrs/wk during school year, 30–40 hrs/wk in summer. Requires graduation Dec 2026 or later. CMM/dimensional-analysis work in production environment.",
  },
  {
    Company: "GE Vernova (Nuclear)",
    "Role Title": "Nuclear Engineering Co-Op/Intern",
    Discipline: "Nuclear / Mechanical / Chemical / Electrical / Materials / Controls / Civil-Structural Engineering",
    Season: "Spring 2027",
    Location: "Wilmington, NC",
    "Distance from Boston, MA (mi, approx.)": 720,
    Pay: "$1,000–$2,000/week (varies by degree level)",
    "Application Link": "https://careers.gevernova.com/ge-vernova-nuclear-engineering-co-op-intern-spring-2027/job/R5048552",
    "Link Verified": "Yes — fetched directly, confirmed OPEN, posted Aug 7, 2026 (within freshness window)",
    Notes: "Housing/relocation assistance if 50+ mi from site. Must be work-authorized without sponsorship.",
  },
  {
    Company: "GE Vernova (Nuclear)",
    "Role Title": "Nuclear – Field Services Spring Internship",
    Discipline: "Engineering / Engineering Technology",
    Season: "Spring 2027 (starts January 2027)",
    Location: "Wilmington, NC (up to 70% travel to nuclear plant sites)",
    "Distance from Boston, MA (mi, approx.)": 720,
    Pay: "$1,000–$2,000/week (varies by experience)",
    "Application Link": "https://careers.gevernova.com/ge-vernova-nuclear-field-services-spring-internship-2027/job/R5049161",
    "Link Verified": "Yes — fetched directly, confirmed OPEN, posted Aug 7, 2026 (within freshness window)",
    Notes: "Housing/relocation assistance if 50+ mi from site. Must be work-authorized without sponsorship.",
  },
  {
    Company: "NASA (Pathways Internship Program)",
    "Role Title": "Pathways Internship – various engineering disciplines",
    Discipline: "Mechanical / Systems / Aerospace (varies by center & opening)",
    Season: "Spring 2027 (apply via USAJOBS; deadline Sept 14, 2026)",
    Location: "Varies — multiple NASA centers nationwide",
    "Distance from Boston, MA (mi, approx.)": null,
    Pay: "Federal student stipend scale, varies by degree level (not a fixed rate)",
    "Application Link": "https://www.usajobs.gov/",
    "Link Verified": "Yes — usajobs.gov is the live, official application portal (this is a program, not a single job req — search USAJOBS for open NASA Pathways postings)",
    Notes: "US citizenship required. Cumulative GPA 2.9+ required. Spring 2027 window opens on USAJOBS in fall 2026.",
  },
  // --- Added 2026-09-19 routine run ---
  {
    Company: "MIT Lincoln Laboratory",
    "Role Title": "Microfabrication Industrial Engineering Co-Op (Group 08-35, Microelectronics Laboratory)",
    Discipline: "Industrial Engineering (Systems Eng/Ops Research/Manufacturing Eng/CS also accepted)",
    Season: "Jan–August 2027 (spans Winter 2026/2027 and Spring 2027)",
    Location: "Lexington, MA",
    "Distance from Boston, MA (mi, approx.)": 13,
    Pay: "$24.50–$31.00/hr (2025 technical co-op rate; subject to review for 2027)",
    "Application Link": "https://careers.ll.mit.edu/job/Lexington-Microfab-Industrial-Eng_-Co-Op-Microelectronics-Laboratory-%28Jan-August-2027%29-Group-08-35-MA-02420/1370647300/",
    "Link Verified": "Yes — fetched directly, active Apply link, no closed/expired banner. Posted Aug 26, 2026.",
    Notes: "Requires US citizenship + eligibility for Secret-level DoD clearance. Sibling req 'Microfabrication Engineering Co-Op' (same Jan–Aug 2027 window, Group 08-35) also exists but wasn't separately fetched.",
  },
  {
    Company: "Draper Laboratory",
    "Role Title": "Systems Engineering Co-Op (Spring 2027)",
    Discipline: "Systems Design Engineering",
    Season: "Spring 2027",
    Location: "Cambridge, MA",
    "Distance from Boston, MA (mi, approx.)": 3,
    Pay: "Not stated on posting",
    "Application Link": "https://draper.wd5.myworkdayjobs.com/Draper_Careers/job/Cambridge-MA/Systems-Engineering-Co-Op--Spring-2027-_JR002882",
    "Link Verified": "Yes — upgraded 2026-09-20: confirmed via direct fetch of Draper's Workday CXS job API (title, description, pay range all returned), posted ~9 days ago as of this check.",
    Notes: "GAD division placement. Pay $20.00-$45.00/hr per posting.",
  },
  {
    Company: "Draper Laboratory",
    "Role Title": "Electro-Mechanical Instrument Co-op (Spring 2027)",
    Discipline: "Hardware / Mechanical Engineering",
    Season: "Spring 2027",
    Location: "Cambridge, MA",
    "Distance from Boston, MA (mi, approx.)": 3,
    Pay: "Not stated on posting",
    "Application Link": "https://draper.wd5.myworkdayjobs.com/Draper_Careers/job/Cambridge-MA/Electro-Mechanical-Instrument-Co-op--Spring-2027-_JR002883-1",
    "Link Verified": "Yes — upgraded 2026-09-20: confirmed via direct fetch of Draper's Workday CXS job API (title, description, pay range all returned), posted ~20 days ago as of this check.",
    Notes: "US Citizenship required — Draper cannot sponsor/hire H1B or Student Visa holders; dual citizens not eligible. CAD (Creo/SolidWorks), FEA (ANSYS/COMSOL) skills mentioned. Pay $20.00-$45.00/hr per posting.",
  },
  {
    Company: "Amazon Robotics",
    "Role Title": "Industrial Development Engineer Intern/Co-op, ROBOTICS – 2027",
    Discipline: "Industrial Engineering / Robotics Manufacturing & Technical Operations",
    Season: "2027 (single req covers summer intern, spring co-op, and fall co-op placement — Spring 2027 placement is NOT guaranteed)",
    Location: "Westborough, MA (also Arlington, VA and North Reading, MA)",
    "Distance from Boston, MA (mi, approx.)": 35,
    Pay: "$82,450/year (Amazon standard pay-transparency disclosure for this req)",
    "Application Link": "https://www.amazon.jobs/en/jobs/10536817/industrial-development-engineer-intern-co-op-robotics-2027",
    "Link Verified": "Yes — fetched directly, page loaded fully, role open. UPDATE (2026-09-20): posting text now explicitly reads 'Robotics Industrial Engineer 2027 summer intern, spring co-op, and fall co-op roles' — confirms Spring 2027 co-op is one of the terms this req covers (previously ambiguous).",
    Notes: "Requires graduation between Dec 2026–Aug 2027. Prior req IDs for this role (e.g. 3088739, the 2026-cycle version) are confirmed dead (404).",
  },
  // --- Added 2026-09-20 routine run ---
  {
    Company: "Formlabs",
    "Role Title": "Mechanical Engineering Intern (Winter/Spring 2027)",
    Discipline: "Mechanical / Hardware Engineering",
    Season: "Winter/Spring 2027 (January–April)",
    Location: "Somerville, MA",
    "Distance from Boston, MA (mi, approx.)": 3,
    Pay: "$1,575–$1,950/week (salaried, full-time)",
    "Application Link": "https://careers.formlabs.com/job/8130829/apply/?gh_jid=8130829",
    "Link Verified": "Yes — fetched directly, page live, season/location/pay confirmed in posting text.",
    Notes: "Boston metro. Portfolio of prior engineering work required — application not considered without one.",
  },
  {
    Company: "Formlabs",
    "Role Title": "Hardware Systems Integration Intern (Winter/Spring 2027)",
    Discipline: "Hardware / Electro-Mechanical Engineering",
    Season: "Winter/Spring 2027 (January–April)",
    Location: "Somerville, MA",
    "Distance from Boston, MA (mi, approx.)": 3,
    Pay: "Not stated on posting",
    "Application Link": "https://careers.formlabs.com/job/8172004/apply/?gh_jid=8172004",
    "Link Verified": "Yes — fetched directly, page live, title/season/location confirmed in posting text.",
    Notes: "Boston metro. Portfolio of prior engineering work required.",
  },
  {
    Company: "Eaton",
    "Role Title": "ETO Engineering Co-op",
    Discipline: "Mechanical, Industrial, or Electrical Engineering",
    Season: "Fall 2026 or Spring 2027 (posting states either start date is acceptable)",
    Location: "Syracuse, NY",
    "Distance from Boston, MA (mi, approx.)": 260,
    Pay: "$24.92/hr",
    "Application Link": "https://eaton.eightfold.ai/careers/job/687236797540",
    "Link Verified": "Yes — verified via Eaton's own public Eightfold job-board API directly (the rendered page is JS-heavy); record shows isPrivate: false (publicly listed/active), created 2026-05-21, last updated 2026-08-12.",
    Notes: "Min GPA 2.8. No visa sponsorship (no CPT/OPT/H-1B support). Must live within ~50 mi of Syracuse, NY — no relocation assistance.",
  },
  {
    Company: "Reframe Systems",
    "Role Title": "Mechanical Engineer (Spring 2027 Co-op)",
    Discipline: "Mechanical Engineering (CAD, welding, machining, fixturing/workcell design)",
    Season: "Spring 2027",
    Location: "Andover, MA (HQ) / FAB1 microfactory, Billerica, MA",
    "Distance from Boston, MA (mi, approx.)": 23,
    Pay: "Not stated on posting",
    "Application Link": "https://jobs.ashbyhq.com/reframesystems/f5275832-8373-4971-b5f6-6aaececcb061",
    "Link Verified": "Yes — verified via Reframe Systems' own public Ashby job-board API directly; record shows isListed: true, publishedAt 2026-08-05, exact worksite address (30 Lowell Junction Rd, Andover MA).",
    Notes: "Small modular-construction/robotics-manufacturing startup, Boston metro (Andover/Billerica). Shop-based role — CAD, welding, machining, fixturing.",
  },
  {
    Company: "General Dynamics Electric Boat",
    "Role Title": "2027 Spring Engineering CO-OP Trainee",
    Discipline: "Mechanical / Structural / Aerospace-Aeronautical / Systems / Naval Architecture / Industrial / Electromechanical / Robotics Engineering (multi-discipline req)",
    Season: "Spring of 2027 (per listing summary)",
    Location: "Groton, CT (co-ops also placed in New London/North Stonington CT, North Kingstown/Newport RI)",
    "Distance from Boston, MA (mi, approx.)": 90,
    Pay: "Not stated on posting",
    "Application Link": "https://jobs.buildsubmarines.com/job/601496955",
    "Link Verified": "Partial — found via GD Electric Boat's own dedicated recruiting site (jobs.buildsubmarines.com) with a specific req ID, mirroring the pattern of GD's known 2026 cycle req. The page itself is behind a Cloudflare bot-check wall — blocked on WebFetch, curl w/ browser UA, and a reader-proxy fetch, all returning a security-verification/CAPTCHA screen. Could not independently confirm live/open status or the exact discipline breakdown. Verify live in-browser before applying.",
    Notes: "Was flagged 'worth re-checking' in the prior run; upgraded from 'no verifiable link' to 'specific req ID found, still blocked'.",
  },
  {
    Company: "Anduril Industries",
    "Role Title": "Winter 2027 Mechanical Engineer Co-op",
    Discipline: "Mechanical Engineering",
    Season: "Winter 2027 (16–24 wks, effectively Jan–Aug 2027 — same calendar window other employers call 'Spring 2027')",
    Location: "Quincy, MA",
    "Distance from Boston, MA (mi, approx.)": 8,
    Pay: "$34–$50/hr",
    "Application Link": "https://job-boards.greenhouse.io/andurilindustries/jobs/5236601007",
    "Link Verified": "Yes — fetched directly on Greenhouse, Apply button live.",
    Notes: "Boston metro (Quincy). Corrects an earlier 'checked' entry for Anduril that only found Summer 2027 postings — this Winter 2027 cohort is a separate, later-posted cycle.",
  },
  {
    Company: "Anduril Industries",
    "Role Title": "Winter 2027 Systems Engineer Co-op",
    Discipline: "Systems Engineering",
    Season: "Winter 2027 (effectively Jan–Aug 2027)",
    Location: "Quincy, MA",
    "Distance from Boston, MA (mi, approx.)": 8,
    Pay: "$40–$55/hr",
    "Application Link": "https://job-boards.greenhouse.io/andurilindustries/jobs/5236599007",
    "Link Verified": "Yes — fetched directly on Greenhouse, Apply button live.",
    Notes: "Boston metro (Quincy). Same cohort/site as the Mechanical Engineer Co-op above.",
  },
  {
    Company: "Rivian",
    "Role Title": "Engineering Intern – Manufacturing Engineering (Spring 2027 Co-Op)",
    Discipline: "Manufacturing Engineering",
    Season: "Spring 2027 Co-Op (Jan–Aug 2027)",
    Location: "Normal, IL",
    "Distance from Boston, MA (mi, approx.)": 1000,
    Pay: "~$25–$51/hr per third-party aggregator; not independently confirmed via direct fetch",
    "Application Link": "https://careers.rivian.com/jobs/33784?lang=en-us",
    "Link Verified": "Yes — fetched directly on Rivian's own careers site, title/location/season confirmed.",
    Notes: "",
  },
  {
    Company: "Rivian",
    "Role Title": "Engineering Intern – Design for Reliability (Spring 2027 Co-Op)",
    Discipline: "Mechanical / Design Engineering",
    Season: "Spring 2027 Co-Op (Jan–Aug 2027)",
    Location: "Irvine, CA",
    "Distance from Boston, MA (mi, approx.)": 2600,
    Pay: "~$26–$45/hr per third-party aggregator; not independently confirmed via direct fetch",
    "Application Link": "https://careers.rivian.com/careers-home/jobs/33705?lang=en-us",
    "Link Verified": "Yes — fetched directly on Rivian's own careers site, title/location/season confirmed.",
    Notes: "",
  },
  {
    Company: "SpaceX",
    "Role Title": "Spring 2027 Engineering Internship/Co-op",
    Discipline: "Engineering (multi-discipline req)",
    Season: "Spring 2027 (start Jan or Mar 2027)",
    Location: "Multiple US sites (incl. Bloomfield, CT — see posting for full list)",
    "Distance from Boston, MA (mi, approx.)": null,
    Pay: "$28–$30/hr",
    "Application Link": "https://job-boards.greenhouse.io/spacex/jobs/8616338002",
    "Link Verified": "Yes — fetched directly on Greenhouse, live.",
    Notes: "Corrects an earlier 'checked' entry that grouped SpaceX with companies having 'no Winter 2026/Spring 2027-specific postings' — this Spring 2027 req is a later-posted exception. Likely requires US person status (ITAR) though not explicitly re-confirmed this session.",
  },
  {
    Company: "Rocket Lab",
    "Role Title": "Mechanical Engineering Intern, Spring 2027",
    Discipline: "Mechanical Engineering",
    Season: "Spring 2027 (start Jan/Feb/Mar 2027)",
    Location: "Long Beach, CA",
    "Distance from Boston, MA (mi, approx.)": 2600,
    Pay: "$28/hr",
    "Application Link": "https://job-boards.greenhouse.io/rocketlab/jobs/7985634003",
    "Link Verified": "Yes — fetched directly on Greenhouse, Apply button live.",
    Notes: "Rocket Lab has ~25 more Spring 2027 postings (propulsion, structural, manufacturing, test) across CA/MD/VA/AZ/CO/NM — none in Boston area, not individually logged.",
  },
  {
    Company: "Rocket Lab",
    "Role Title": "Systems Engineering Intern, Spring 2027",
    Discipline: "Systems Engineering",
    Season: "Spring 2027 (start Jan/Feb/Mar 2027)",
    Location: "Long Beach, CA",
    "Distance from Boston, MA (mi, approx.)": 2600,
    Pay: "$28/hr",
    "Application Link": "https://job-boards.greenhouse.io/rocketlab/jobs/7987044003",
    "Link Verified": "Yes — fetched directly on Greenhouse, Apply button live.",
    Notes: "",
  },
  {
    Company: "Collins Aerospace (RTX)",
    "Role Title": "Project Engineering Co-op (Winter/Spring 2027)",
    Discipline: "Systems / Mechanical Engineering",
    Season: "Winter/Spring 2027 (Jan–Jul/Aug 2027, full-time)",
    Location: "Windsor Locks, CT",
    "Distance from Boston, MA (mi, approx.)": 90,
    Pay: "$37,000–$82,000/yr (RTX co-op band)",
    "Application Link": "https://globalhr.wd5.myworkdayjobs.com/REC_RTX_Ext_Gateway/job/US-CT-WINDSOR-LOCKS-B1A--1-Hamilton-Rd--BLDG-1A/Project-Engineering-Co-op--Winter-Spring-2027-_01872478",
    "Link Verified": "Partial — Workday page blocked automated fetch (blank/JS-rendered). Req ID and Sept 14, 2026 posting date confirmed via aggregator mirror only. Verify live in-browser before applying.",
    Notes: "~1.5 hrs from Boston.",
  },
  {
    Company: "Pratt & Whitney (RTX)",
    "Role Title": "Production Support Engineering Co-op (Winter/Spring 2027)",
    Discipline: "Mechanical / Manufacturing / Aerospace Engineering",
    Season: "Winter/Spring 2027 (Jan–Jul/Aug 2027)",
    Location: "Middletown, CT",
    "Distance from Boston, MA (mi, approx.)": 105,
    Pay: "$37,000–$82,000/yr (RTX co-op band)",
    "Application Link": "https://globalhr.wd5.myworkdayjobs.com/REC_RTX_Ext_Gateway/job/US-CT-MIDDLETOWN-220A--Aircraft-Rd--BLDG-220A/Production-Support-Engineering-Co-op--Winter-Spring-2027-_01872654",
    "Link Verified": "Partial — Workday page blocked automated fetch. Req ID and Sept 13, 2026 posting date confirmed via aggregator mirror only. Verify live in-browser before applying.",
    Notes: "~1.5 hrs from Boston.",
  },
  {
    Company: "RTX (Collins Aerospace)",
    "Role Title": "Certification Engineer Co-Op (Winter/Spring 2027, Onsite)",
    Discipline: "Mechanical / Aerospace / Materials Science / Chemical Engineering",
    Season: "Winter/Spring 2027 (Jan–Jul, two semesters)",
    Location: "Winston-Salem, NC",
    "Distance from Boston, MA (mi, approx.)": 700,
    Pay: "$37,000–$82,000/yr (RTX co-op band)",
    "Application Link": "https://globalhr.wd5.myworkdayjobs.com/REC_RTX_Ext_Gateway/job/US-NC-WINSTON-SALEM-190--190-Oak-Plaza-Blvd--BLDG-190/Certification-Engineer-Co-Op--Winter-Spring-2027--Onsite-_01871317-1",
    "Link Verified": "Partial — Workday page blocked automated fetch. Confirmed via aggregator mirror, posting date Sept 16, 2026. Verify live in-browser before applying.",
    Notes: "",
  },
  {
    Company: "RTX (Collins Aerospace)",
    "Role Title": "Mechanical Engineering Co-op (Winter/Spring 2027)",
    Discipline: "Mechanical Engineering",
    Season: "Winter/Spring 2027 (Jan–Jul/Aug 2027)",
    Location: "Cedar Rapids, IA",
    "Distance from Boston, MA (mi, approx.)": 1130,
    Pay: "$37,000–$82,000/yr (RTX co-op band)",
    "Application Link": "https://globalhr.wd5.myworkdayjobs.com/REC_RTX_Ext_Gateway/job/US-IA-CEDAR-RAPIDS-131--5450-C-Ave-NE--BLDG-131/Mechanical-Engineering-Co-op--Winter-Spring-2027-_01869080",
    "Link Verified": "Partial — Workday page blocked automated fetch. Confirmed via aggregator mirror, posting date Sept 15, 2026. Verify live in-browser before applying.",
    Notes: "",
  },
  {
    Company: "RTX (Collins Aerospace)",
    "Role Title": "Structural Engineering Co-op (Winter/Spring 2027)",
    Discipline: "Structural Engineering",
    Season: "Winter/Spring 2027 (Jan–Jul/Aug 2027)",
    Location: "Jamestown, ND",
    "Distance from Boston, MA (mi, approx.)": 1500,
    Pay: "$37,000–$82,000/yr (RTX co-op band)",
    "Application Link": "https://globalhr.wd5.myworkdayjobs.com/REC_RTX_Ext_Gateway/job/US-ND-JAMESTOWN-P1--2604-Highway-20-N--PLANT-1/Structural-Engineering-Co-op--Winter-Spring-2027-_01873938",
    "Link Verified": "Partial — Workday page blocked automated fetch. Confirmed via aggregator mirror, posting date Sept 14, 2026. Verify live in-browser before applying.",
    Notes: "",
  },
  {
    Company: "Northrop Grumman",
    "Role Title": "2027 Spring Mechanical Engineering Co-op",
    Discipline: "Mechanical Engineering",
    Season: "Spring/Summer 2027 (Jan–Aug 2027)",
    Location: "Chandler, AZ",
    "Distance from Boston, MA (mi, approx.)": 2300,
    Pay: "Bachelor's $18.50–$33.50/hr; Master's $26.25–$41.50/hr",
    "Application Link": "https://ngc.wd1.myworkdayjobs.com/Northrop_Grumman_External_Site/job/United-States-Arizona-Chandler/XMLNAME-2027-Spring-Mechanical-Engineering-Co-op---Chandler-AZ_R10249939",
    "Link Verified": "Partial — Workday page blocked automated fetch. Confirmed via aggregator mirror only. Verify live in-browser before applying.",
    Notes: "",
  },
  {
    Company: "Berkshire Grey",
    "Role Title": "Spring 2027 Hardware Quality Co-op",
    Discipline: "Hardware / Quality Engineering",
    Season: "Spring 2027",
    Location: "Bedford, MA",
    "Distance from Boston, MA (mi, approx.)": 17,
    Pay: "Not stated (aggregator only)",
    "Application Link": "https://berkshiregrey.bamboohr.com/careers/771",
    "Link Verified": "Partial — BambooHR page rendered empty on two direct fetch attempts. Only confirmed via a third-party aggregator (posted ~Sept 1, 2026), not first-hand. Verify live in-browser before applying.",
    Notes: "Boston metro (Bedford).",
  },
  {
    Company: "Emerson",
    "Role Title": "R&D Engineering Co-Op – Spring 2027",
    Discipline: "R&D / Mechanical Engineering",
    Season: "Spring 2027",
    Location: "Cranberry Township, PA",
    "Distance from Boston, MA (mi, approx.)": 570,
    Pay: "Not stated (aggregator only)",
    "Application Link": "https://hdjq.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/26010785",
    "Link Verified": "Partial — Oracle Cloud ATS is JS-rendered, returned empty content on direct fetch. Sourced via aggregator mirror only. Verify live in-browser before applying.",
    Notes: "",
  },
  {
    Company: "Emerson",
    "Role Title": "Project Engineering Co-op – Spring 2027",
    Discipline: "Project / Mechanical Engineering",
    Season: "Spring 2027",
    Location: "Cranberry Township, PA / Blue Bell, PA / Detroit, MI",
    "Distance from Boston, MA (mi, approx.)": 570,
    Pay: "Not stated (aggregator only)",
    "Application Link": "https://hdjq.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/26010587",
    "Link Verified": "Partial — Oracle Cloud ATS is JS-rendered, returned empty content on direct fetch. Sourced via aggregator mirror only. Verify live in-browser before applying.",
    Notes: "",
  },
  {
    Company: "Zipline",
    "Role Title": "Mechanical Engineer Intern",
    Discipline: "Mechanical Engineering",
    Season: "Spring 2027 (Jan–Apr/May)",
    Location: "South San Francisco, CA (or Dallas, TX)",
    "Distance from Boston, MA (mi, approx.)": 2700,
    Pay: "~$60k–$70k annualized (third-party estimate, not stated on posting)",
    "Application Link": "https://www.zipline.com/open-roles/7865253003?gh_jid=7865253003",
    "Link Verified": "Partial — fetched directly, confirmed exact title and 'Spring 2027' wording on the page, but page is JS-rendered so Apply-button/open status could not be independently confirmed from the fetch alone. Corroborated as currently listed by two other independent sources (2026-09-20).",
    Notes: "Design/build/test electro-mechanical systems for autonomous drone delivery. Requires ≥2nd year undergrad completed; masters/PhD also eligible.",
  },
  // --- Added 2026-09-20 ~13:00 UTC routine run ---
  {
    Company: "Applied Materials",
    "Role Title": "2027 Spring Mechanical Engineer Co-op",
    Discipline: "Mechanical Engineering",
    Season: "Spring 2027 (start January 2027)",
    Location: "Gloucester, MA",
    "Distance from Boston, MA (mi, approx.)": 30,
    Pay: "$31–33/hr",
    "Application Link": "https://amat.wd1.myworkdayjobs.com/external/job/GloucesterMA/XMLNAME-2027-Spring-Mechanical-Engineer-Co-op--Gloucester-MA-_R2628290",
    "Link Verified": "Partial — Workday page blocked automated fetch (JS-rendered, empty). Confirmed via a dreamworkhq aggregator mirror quoting the exact title, season, location, pay, and req ID, posted ~1 week ago as of 2026-09-20. Verify live in-browser before applying.",
    Notes: "Boston metro (Gloucester, MA). A sibling req, '2027 Spring Product Quality Engineer Co-op' at the same site, also exists but is a different discipline — not added.",
  },
  {
    Company: "Sanofi (Genzyme)",
    "Role Title": "2027 Spring Co-Op Opportunities",
    Discipline: "Manufacturing / Process Engineering (biopharma — MSAT: Manufacturing Science & Technology)",
    Season: "Spring 2027 (6-month, starting January 2027)",
    Location: "Framingham, MA",
    "Distance from Boston, MA (mi, approx.)": 20,
    Pay: "$32–55/hr",
    "Application Link": "https://jobs.sanofi.com/en/job/framingham/2027-spring-co-op-opportunities-framingham-ma/2649/41259847040",
    "Link Verified": "Yes — fetched directly, page live, active 'Apply Now' button present. Posting states it closes November 14, 2026.",
    Notes: "Boston metro (Framingham). Umbrella posting covering multiple functional tracks (HSE, Cell Culture Development, Downstream/Upstream MSAT, Supply Chain Planning, Drug Product Development) — biopharma manufacturing/process engineering, not classic mechanical. A second Sanofi req ('GMU CMC Purification Process Development,' Waltham MA) surfaced but wasn't independently verified — likely another slot in this same program, not double-counted.",
  },
  // --- Added 2026-09-20 ~19:00 UTC routine run ---
  {
    Company: "GE Aerospace",
    "Role Title": "Engines Engineering Co-op – US – Spring 2027",
    Discipline: "Aerospace / Mechanical Engineering",
    Season: "Spring 2027",
    Location: "Lynn, MA or Evendale/Cincinnati, OH (dual-location req)",
    "Distance from Boston, MA (mi, approx.)": 0,
    Pay: "Starts at $20/hr, increases per undergrad class year",
    "Application Link": "https://geaerospace.wd5.myworkdayjobs.com/en-US/GE_ExternalSite/job/Evendale/Engines-Engineering-Co-op---US---Spring-2027_R5029617-1",
    "Link Verified": "Yes — fetched directly via GE's Workday CXS job API, full description confirmed.",
    Notes: "Requires 'US Person' status (citizen/LPR/asylee/refugee) for export-controlled work; no visa sponsorship; relocation/housing assistance provided. This is the first live GE Aerospace Spring 2027 req found after 4 prior runs found only dead/expired reqs — Lynn, MA option makes this a Boston-metro fit.",
  },
  {
    Company: "GE Aerospace",
    "Role Title": "Structures Intern/Co-op – ACSC – Cincinnati, OH – Spring 2027",
    Discipline: "Structural / Manufacturing / Materials Engineering",
    Season: "Spring 2027",
    Location: "Springdale (Cincinnati), OH",
    "Distance from Boston, MA (mi, approx.)": 750,
    Pay: "Not stated on posting",
    "Application Link": "https://geaerospace.wd5.myworkdayjobs.com/en-US/GE_ExternalSite/job/Springdale/Structures-Intern-Co-op---ACSC---Cincinnati--OH---Spring-2027_R5039588-1",
    "Link Verified": "Yes — fetched directly via GE's Workday CXS job API, full description confirmed.",
    Notes: "Accepted majors: Aerospace, Manufacturing, Mechanical, Materials, Industrial Engineering. Not Boston-area.",
  },
  {
    Company: "Insulet",
    "Role Title": "Co-op, R&D Mechanical Engineering (January–June 2027, Hybrid)",
    Discipline: "Mechanical Engineering",
    Season: "January 11, 2027 – June 30, 2027",
    Location: "Acton, MA",
    "Distance from Boston, MA (mi, approx.)": 25,
    Pay: "$25.00–$34.00/hr",
    "Application Link": "https://insulet.wd5.myworkdayjobs.com/en-US/insuletcareers/job/Acton-Massachusetts/Co-op--R-D-Mechanical-Engineering--January---June-2027--Hybrid-_REQ-2026-18007",
    "Link Verified": "Yes — full description fetched directly via Workday, posted 4 days ago.",
    Notes: "Boston metro (Acton). Medical device (insulin pump) manufacturer. Not eligible for visa sponsorship; requires US work authorization without future sponsorship needs. Part of a large batch of Insulet Acton co-ops opened this cycle — see sibling reqs below.",
  },
  {
    Company: "Insulet",
    "Role Title": "Co-op, Manufacturing Engineering (January–June 2027, Onsite)",
    Discipline: "Manufacturing Engineering",
    Season: "January 11, 2027 – June 30, 2027",
    Location: "Acton, MA",
    "Distance from Boston, MA (mi, approx.)": 25,
    Pay: "$25.00–$34.00/hr",
    "Application Link": "https://insulet.wd5.myworkdayjobs.com/en-US/insuletcareers/job/Acton-Massachusetts/Co-op--Manufacturing-Engineering--January---June-2027--Onsite-_REQ-2026-18078",
    "Link Verified": "Yes — full description fetched directly via Workday, posted 5 days ago.",
    Notes: "Boston metro (Acton). No visa sponsorship.",
  },
  {
    Company: "Insulet",
    "Role Title": "Co-op, Systems Engineering (January–June 2027, Hybrid)",
    Discipline: "Systems Engineering",
    Season: "January 11, 2027 – June 30, 2027",
    Location: "Acton, MA",
    "Distance from Boston, MA (mi, approx.)": 25,
    Pay: "$25.00–$34.00/hr",
    "Application Link": "https://insulet.wd5.myworkdayjobs.com/en-US/insuletcareers/job/Acton-Massachusetts/Co-op--Systems-Engineering--January-June-2027--Hybrid-_REQ-2026-18061",
    "Link Verified": "Yes — full description fetched directly via Workday, posted 5 days ago.",
    Notes: "Boston metro (Acton). No visa sponsorship.",
  },
  {
    Company: "Insulet",
    "Role Title": "Co-op, Mechanical Lifecycle (January–June 2027, Onsite)",
    Discipline: "Mechanical Engineering",
    Season: "January–June 2027 (per title)",
    Location: "Acton, MA",
    "Distance from Boston, MA (mi, approx.)": 25,
    Pay: "Not independently confirmed (see $25–34/hr range on sibling reqs)",
    "Application Link": "https://insulet.wd5.myworkdayjobs.com/en-US/insuletcareers/job/Acton-Massachusetts/Co-op--Mechanical-Lifecycle--January---June-2027--Onsite-_REQ-2026-18155",
    "Link Verified": "Partial — confirmed live and current via direct query of Insulet's own Workday jobs-search API (real title/location/posted-date, not an aggregator), posted 5 days ago. Full job-description body was not individually opened — spot-check before applying.",
    Notes: "Boston metro (Acton). One of a batch of Insulet Acton co-ops opened this cycle alongside the fully-verified R&D Mechanical/Manufacturing/Systems reqs above.",
  },
  {
    Company: "Insulet",
    "Role Title": "Co-op, R&D Manufacturing (January–June 2027, Onsite)",
    Discipline: "Manufacturing Engineering",
    Season: "January–June 2027 (per title)",
    Location: "Acton, MA",
    "Distance from Boston, MA (mi, approx.)": 25,
    Pay: "Not independently confirmed (see $25–34/hr range on sibling reqs)",
    "Application Link": "https://insulet.wd5.myworkdayjobs.com/en-US/insuletcareers/job/Acton-Massachusetts/Co-op--R-D-Manufacturing--January-June-2027--Onsite-_REQ-2026-18069",
    "Link Verified": "Partial — confirmed live via direct Workday jobs-search API query, posted 5 days ago. Full description not individually opened — spot-check before applying.",
    Notes: "Boston metro (Acton).",
  },
  {
    Company: "Insulet",
    "Role Title": "Graduate Co-op, Manufacturing Engineering (January–June 2027, Onsite)",
    Discipline: "Manufacturing Engineering (graduate-level)",
    Season: "January–June 2027 (per title)",
    Location: "Acton, MA",
    "Distance from Boston, MA (mi, approx.)": 25,
    Pay: "Not independently confirmed (see $25–34/hr range on sibling reqs)",
    "Application Link": "https://insulet.wd5.myworkdayjobs.com/en-US/insuletcareers/job/Acton-Massachusetts/Co-op--Manufacturing-Graduate--January---June-2027--Onsite-_REQ-2026-18086",
    "Link Verified": "Partial — confirmed live via direct Workday jobs-search API query, posted 5 days ago. Full description not individually opened — spot-check before applying.",
    Notes: "Boston metro (Acton). Labeled 'Graduate Co-op' — confirm eligibility if Hamza is undergraduate.",
  },
  {
    Company: "Insulet",
    "Role Title": "Co-op, Supplier Development Engineering - Mechanical (January–June 2027)",
    Discipline: "Mechanical / Supplier Quality Engineering",
    Season: "January–June 2027 (per title)",
    Location: "Acton, MA",
    "Distance from Boston, MA (mi, approx.)": 25,
    Pay: "Not independently confirmed (see $25–34/hr range on sibling reqs)",
    "Application Link": "https://insulet.wd5.myworkdayjobs.com/insuletcareers/job/Acton-Massachusetts/Co-op--Supplier-Development-Engineering---Mechanical--January-June-2027--Onsite-_REQ-2026-18209",
    "Link Verified": "Partial — title/season/pay/location confirmed via a Dreamwork aggregator mirror that quotes Insulet's own Workday application URL directly (not a synthesized link); the live Workday page itself is JS-rendered and returned blank on direct fetch. Spot-check before applying.",
    Notes: "Boston metro (Acton).",
  },
  {
    Company: "Insulet",
    "Role Title": "Co-op, Systems Engineering - Design Verification (January–June 2027)",
    Discipline: "Systems Engineering",
    Season: "January–June 2027 (per title)",
    Location: "Acton, MA",
    "Distance from Boston, MA (mi, approx.)": 25,
    Pay: "Not independently confirmed (see $25–34/hr range on sibling reqs)",
    "Application Link": "https://insulet.wd5.myworkdayjobs.com/insuletcareers/job/Acton-Massachusetts/Co-op--Systems-Engineering---Design-Verification--January---June-2027--Onsite-_REQ-2026-18144-1",
    "Link Verified": "Partial — title/season/pay/location confirmed via a Dreamwork aggregator mirror that quotes Insulet's own Workday application URL directly; the live Workday page itself is JS-rendered and returned blank on direct fetch. Spot-check before applying.",
    Notes: "Boston metro (Acton).",
  },
  {
    Company: "Insulet",
    "Role Title": "Co-op, Life Cycle Engineering - Systems (January–June 2027)",
    Discipline: "Systems Engineering",
    Season: "January–June 2027 (per title)",
    Location: "Acton, MA",
    "Distance from Boston, MA (mi, approx.)": 25,
    Pay: "Not independently confirmed (see $25–34/hr range on sibling reqs)",
    "Application Link": "https://insulet.wd5.myworkdayjobs.com/insuletcareers/job/Acton-Massachusetts/Co-op--Life-Cycle-Engineering---Systems--January---June-2027--Hybrid-_REQ-2026-18149",
    "Link Verified": "Partial — title/season/pay/location confirmed via a Dreamwork aggregator mirror that quotes Insulet's own Workday application URL directly; the live Workday page itself is JS-rendered and returned blank on direct fetch. Spot-check before applying.",
    Notes: "Boston metro (Acton). Most recently posted of the Insulet batch.",
  },
  {
    Company: "GE HealthCare",
    "Role Title": "Infant Care V&V Engineering Co-op - Spring 2027",
    Discipline: "Mechanical / Verification & Validation Engineering",
    Season: "Spring 2027",
    Location: "Waukesha, WI",
    "Distance from Boston, MA (mi, approx.)": 950,
    Pay: "Not stated on posting",
    "Application Link": "https://gehc.wd5.myworkdayjobs.com/en-US/GEHC_ExternalSite/job/Waukesha/Infant-Care-V-V-Engineering-Co-op_R4046324-1",
    "Link Verified": "Yes — full description fetched directly via Workday CXS API, posted 2 days ago.",
    Notes: "Accepts Mechanical, Electrical, Computer, and Biomedical Engineering majors — verification/test focus, not pure design. Minimum 20-week commitment, onsite Waukesha WI, no visa sponsorship. Not Boston-area.",
  },
  {
    Company: "GE Vernova",
    "Role Title": "Nuclear Engineering Co-Op/Intern - Spring 2027",
    Discipline: "Nuclear / Industrial Engineering",
    Season: "Spring 2027",
    Location: "Wilmington, NC",
    "Distance from Boston, MA (mi, approx.)": 750,
    Pay: "$1,000–$2,000/week (varies by class year)",
    "Application Link": "https://careers.gevernova.com/ge-vernova-nuclear-engineering-co-op-intern-spring-2027/job/R5048552",
    "Link Verified": "Yes — fetched directly, structured JSON-LD job data embedded in the page confirmed title, pay, address, and datePosted (2026-09-11).",
    Notes: "GE Vernova Hitachi Nuclear Energy (GVH) business. Not Boston-area.",
  },
];

const checked = [
  { Company: "BWX Technologies (Euclid, OH)", "Role(s) Checked": "Materials Engineering Intern/Co-Op; Manufacturing Engineer Intern/Co-Op", Reason: "Both confirmed FILLED when opened directly (checked Aug 21, 2026)" },
  { Company: "Symbotic (Wilmington, MA)", "Role(s) Checked": "Systems Engineer Co-Op; Machine Learning Intern; Hardware Engineer Intern", Reason: "All specific req links 404'd; live careers page currently shows zero intern/co-op postings, only New Grad roles (checked Aug 21, 2026)" },
  { Company: "Amazon Robotics (Westborough, MA)", "Role(s) Checked": "Industrial Engineer Intern/Co-op; Process Engineer Intern/Co-op", Reason: "Specific job IDs found via search returned 404 (expired/removed) when opened directly" },
  { Company: "Cummins (Columbus, IN)", "Role(s) Checked": "Product Engineering; Materials Science & Engineering; Systems Reliability Engineering Co-Op", Reason: "Cummins.jobs is a JS-rendered SPA — could not confirm season or open status via automated fetch; not included without verification" },
  { Company: "Textron Aviation", "Role(s) Checked": "Spring Co-Op – Electronics Modules Engineer", Reason: "Could not confirm which year (2026 vs 2027) the listing covers; careers.textron.com blocked automated verification" },
  { Company: "GD Electric Boat", "Role(s) Checked": "Engineering Co-Op Trainee", Reason: "Only found a 'Spring 2026' cohort posting (already past) — Spring 2027 cycle not yet posted as of search date" },
  { Company: "Tesla / Apple / Google / Meta / Amazon Lab126 / NVIDIA", "Role(s) Checked": "Various hardware/mechanical searches", Reason: "No Winter 2026/Spring 2027-specific postings found for these disciplines (their volume is overwhelmingly Summer 2027); Apple's 'Hardware Undergrad Engineering' reqs appear evergreen with no season stated. NOTE (2026-09-19): SpaceX has since been found to have a genuine Spring 2027 posting — moved to `rows`; removed from this exclusion group." },
  { Company: "GE Aerospace", "Role(s) Checked": "Manufacturing Engineering Co-op Spring 2027 (x2 reqs); Engines Engineering Co-op Spring 2027; Lynn, MA CNC Trainee Co-Op", Reason: "All 4 specific Spring 2027 reqs found via search had already closed ('no longer posted') when opened directly — this employer's Spring cohort appears to cycle very fast. Worth re-checking careers.geaerospace.com periodically for new Spring 2027 reqs." },
  { Company: "RTX / Raytheon / Collins Aerospace / Pratt & Whitney", "Role(s) Checked": "Spring 2027 co-op search on careers.rtx.com", Reason: "careers.rtx.com search endpoint blocked automated fetch (403); found one Raytheon 'Systems Engineer Co-op (Remote)' but it targets a Summer 2026 start, not Winter 2026/Spring 2027 — excluded on season grounds" },
  { Company: "Anduril Industries", "Role(s) Checked": "2027 Mechanical Engineer Intern; 2027 Manufacturing Engineer Intern (Boston, MA location available)", Reason: "Confirmed Summer 2027 only, not Winter/Spring — excluded on season grounds despite the attractive Boston location. UPDATE (2026-09-19): a separate 'Winter 2027' cohort (effectively Jan–Aug 2027) was found live at Quincy, MA — Mechanical and Systems Engineer Co-ops moved to `rows`." },
  { Company: "Anduril Industries", "Role(s) Checked": "Winter 2027 Electrical Engineer Co-op (Quincy, MA)", Reason: "2026-09-19: Confirmed open/live at the same Quincy, MA site as the Mechanical/Systems co-ops added to `rows`, but excluded here — electrical engineering is outside Hamza's target disciplines." },
  { Company: "Draper Laboratory (Cambridge, MA)", "Role(s) Checked": "Current-openings portal (redirects to Workday)", Reason: "Draper's own site confirms co-ops run fall/spring, but the live openings portal is a JS-rendered Workday page that blocked automated fetch — no specific Spring 2027 req could be confirmed. Worth checking manually (this would be a very close Boston option)." },
  { Company: "MIT Lincoln Laboratory (Lexington, MA)", "Role(s) Checked": "careers.ll.mit.edu search", Reason: "Only Summer 2026 reqs found (e.g. Mechanical/Optical Engineering SRP Intern) — no Spring 2027-specific postings live yet as of search date. Also close to Boston if it opens later." },
  { Company: "Lockheed Martin", "Role(s) Checked": "lockheedmartinjobs.com search for 'Spring 2027'", Reason: "Only found Spring 2026 co-ops (already past); direct search-jobs URL 404'd on retry — no confirmed Spring 2027 req found this session" },
  { Company: "GE Aerospace (Lynn, MA)", "Role(s) Checked": "Lynn CNC Trainee Co-Op; Lynn Carpentry Trainee Co-Op; CNC Programmer Co-op Fall 2026; Manufacturing Engineering Co-op Spring 2027; Engines Engineering Co-op Spring 2027 (Computer/Software track)", Reason: "2026-09-19: All previously-known reqs re-checked directly — now return 'no longer posted' or HTTP 410 Gone. One general Engines Eng Co-op (Cincinnati/Lynn) exists on an aggregator but is flagged EXPIRED there; no live company-site URL found. Worth periodic re-checking of careers.geaerospace.com/global/en/lynn." },
  { Company: "Draper Laboratory", "Role(s) Checked": "Sensor Electrical Engineering Co-op (Spring 2027); Optics-Physics Sensor Engineering Co-op (Spring 2027)", Reason: "2026-09-19: Both confirmed live/open on draper.com's own listings page but excluded — electrical/optics engineering discipline, outside Hamza's target list. (Systems Engineering Co-Op and Electro-Mechanical Instrument Co-op from the same posting batch DID qualify and were added to `rows`.)" },
  { Company: "Symbotic (Wilmington, MA)", "Role(s) Checked": "Full careers.symbotic.com/careers/jobs listing + student/grad opportunities page", Reason: "2026-09-19 re-check: still zero internship/co-op postings; only 'Skillbridge' military-transition fellowships found under a co-op search filter, wrong program entirely." },
  { Company: "Amazon Robotics (Westborough, MA)", "Role(s) Checked": "Old job ID 3088739 (2026-cycle Industrial Engineer Intern/Co-op)", Reason: "2026-09-19: confirmed HTTP 404, dead. Superseded by new req 10536817 (2027 cycle), which was added to `rows` with a season caveat." },
  { Company: "BAE Systems (Nashua, NH)", "Role(s) Checked": "Systems Eng Intern III; Software Eng Intern I/III; EE/CE/RF Intern III; Mechanical Engineering Intern III; Industrial Engineering Co-Op (Fall Semester 2026)", Reason: "2026-09-19: All current postings are explicitly Summer 2027 — wrong season. The one Fall 2026 posting from a prior check now returns HTTP 410 Gone." },
  { Company: "Textron Aviation", "Role(s) Checked": "'Spring Co-Op – Electronics Modules Engineer'", Reason: "2026-09-19 re-check: still cannot confirm which year this posting covers — careers.textron.com remains JS-rendered/blocked to automated fetch; only aggregator mirror found is a stale 2024 cache. No other qualifying Spring 2027/Winter 2026 postings found at Textron, Bell, or Textron Systems in target disciplines." },
  { Company: "General Dynamics Electric Boat (Groton, CT)", "Role(s) Checked": "'2027 Spring Engineering Co-Op Trainee'", Reason: "2026-09-19: Search evidence (job-aggregator snapshot, distinct from the already-past Spring 2026 cohort) suggests a new Spring 2027 cycle exists, but both the aggregator page and the official portals (ebcareers.com, careers-gdeb.icims.com) blocked direct fetch — no verifiable specific req link found, so not added to `rows`. Worth checking ebcareers.com/careers-gdeb.icims.com directly in-browser next run." },
  { Company: "Lockheed Martin / Sikorsky (Stratford, CT)", "Role(s) Checked": "lockheedmartinjobs.com legacy links; new careers.lockheedmartin.com search", Reason: "2026-09-19: legacy job-search URLs now 404 (site appears migrated); new careers site's search endpoint also unreachable via fetch. No Spring 2027 co-op/internship located this session." },
  { Company: "L3Harris", "Role(s) Checked": "'Intern, Software Engineer Spring 2027' (Greenville, TX); 'Electrical Engineer Intern B Spring Co-op'", Reason: "2026-09-19: Only software/electrical Spring 2027 co-ops found — discipline mismatch, no mechanical/structural/systems reqs located." },
  { Company: "Leidos", "Role(s) Checked": "Spring 2027 co-op search", Reason: "2026-09-19: Only software/computer engineering co-ops found (Reston VA, Bethesda MD) — discipline mismatch." },
  { Company: "MIT Lincoln Laboratory (Lexington, MA)", "Role(s) Checked": "Rapid Prototyping Aero/Mech Co-Op", Reason: "2026-09-19: Confirmed open via direct fetch, but posting states 'Fall 2026' only with no stated extension into winter/spring — excluded on season grounds. (A separate Microfabrication Industrial Eng Co-Op, Jan–Aug 2027, DID qualify and was added to `rows`.)" },
  { Company: "Boston Dynamics (Waltham, MA)", "Role(s) Checked": "Mechanical Engineering Intern (req R2495)", Reason: "2026-09-19: Season unstated/unclear on this specific req — excluded. (A separate 'Mechanical Engineering Co-Op' req, Spring 2027, DID have a stated season and was added to `rows` as Partial.)" },
  { Company: "Eaton", "Role(s) Checked": "Co-op Design Engineering (Spring 2027), Jackson, MS", Reason: "2026-09-19: A Spring 2027 co-op wave appears to exist generally ($22–28/hr range per search), but the specific link found (fairygodboss listing) now 404s and no working replacement URL could be located — not added without a verifiable link. Worth re-checking." },
  { Company: "Cummins (Columbus, IN)", "Role(s) Checked": "Career board general search", Reason: "2026-09-19 re-check: career board explicitly shows 'No jobs currently found'; next cycle (Summer 2027) not expected to post until ~Dec 2026." },
  { Company: "iRobot / Vicarious Surgical / Desktop Metal / Markforged / Vecna Robotics / Locus Robotics / PTC / Analog Devices", "Role(s) Checked": "Careers pages and Greenhouse boards for Boston-area robotics/hardware companies", Reason: "2026-09-19: No live Winter 2026/Spring 2027 co-op or intern postings found. iRobot: only an already-past Spring 2026 posting. Vicarious Surgical: careers page/Greenhouse errored out. Desktop Metal/Markforged: Greenhouse board has zero internships posted. Vecna: no listings. Locus Robotics: only Summer 2026 and an apparently-expired Fall 2026 posting. PTC: only standard Summer program. Analog Devices: Spring/Fall co-ops are a standing program but no Spring 2027 req posted yet (expected ~Oct/Nov 2026)." },
  { Company: "Caterpillar / John Deere / Honeywell / 3M / GM / Ford / Stellantis / Lucid Motors / Stanley Black & Decker", "Role(s) Checked": "General co-op/intern search, target disciplines", Reason: "2026-09-19: Confirmed postings found are Summer 2027 only, or (Caterpillar) the application window already closed (Aug 14, 2026). No Winter 2026/Spring 2027-specific reqs located." },
  { Company: "Rockwell Automation / Parker Hannifin", "Role(s) Checked": "General co-op/intern search", Reason: "2026-09-19: No specific postings found — only general recruiting-season descriptions." },
  { Company: "Danaher", "Role(s) Checked": "Product Development Engineering Co-op (Jan 2027 start)", Reason: "2026-09-19: Confirmed posting exists but is located in Vancouver, BC, Canada — excluded on location (outside the US), not season." },
  { Company: "Firefly Aerospace / Sierra Space", "Role(s) Checked": "General co-op/intern search", Reason: "2026-09-19: Only Summer 2026/general 'year-round' postings found; Spring 2027 cycle not live yet (Sierra Space's next cycle not expected until ~Sept 2026 onward)." },
  { Company: "MathWorks (Natick, MA)", "Role(s) Checked": "EDG internship listing", Reason: "2026-09-19: Listing mentions 'Spring, Summer, Fall' cohorts generically but carries no year/season tag on the specific req — appears evergreen, could not confirm as Spring 2027." },
  { Company: "CIRTEC Medical", "Role(s) Checked": "General co-op/intern search", Reason: "2026-09-19: Only generic/Summer, California-based postings found — nothing Winter 2026/Spring 2027 or Boston-area." },
  { Company: "Relativity Space", "Role(s) Checked": "'2027 Mechanical/Electrical Engineer Intern' (lists Boston as a possible site)", Reason: "2026-09-19: Appears to be part of the Summer 2027 program (12-week internship, application window opening ~Sept 2026); could not access job-boards.greenhouse.io/rsinternboard directly (404) to confirm season wording — excluded pending clearer evidence." },
  // --- Added 2026-09-20 routine run ---
  { Company: "Textron Aviation", "Role(s) Checked": "'Spring Co-Op – Electronics Modules Engineer'", Reason: "2026-09-20 re-check: no change. careers.textron.com confirmed to be a Nuxt.js SPA (empty shell on direct fetch, API endpoint redirects back to shell). Aggregator mirror (JobzMall) shows a stale 2024 posting for this exact title/location (Wichita, KS) — likely a recycled listing page, not a live 2027 req. Still cannot confirm year." },
  { Company: "RTX Massachusetts sites (Andover / Tewksbury)", "Role(s) Checked": "careers.rtx.com site search for MA-located Winter/Spring 2027 co-ops", Reason: "2026-09-20: No qualifying co-op found — only a Summer 2027 internship (not co-op) and full-time roles at MA sites. All confirmed Winter/Spring 2027 co-op reqs remain at Jamestown ND and Cedar Rapids IA (already in `rows`), none in MA." },
  { Company: "Analog Devices / Sierra Space / Danaher (US) / Caterpillar", "Role(s) Checked": "Quick re-check for newly-opened Spring 2027 cycles", Reason: "2026-09-20: No change — nothing new surfaced; consistent with prior 'not yet posted' finding." },
  { Company: "Olympus (Westborough, MA)", "Role(s) Checked": "Manufacturing Engineering Co-Op", Reason: "2026-09-20: Only directly-openable listing was a Jan–June 2026 cohort, confirmed CLOSED ('no longer accepting applications'). Aggregator text mentions a possible 'Jan–June 2027' version but could not be independently verified (source JS-rendered, API query 404'd) — excluded pending better verification." },
  { Company: "Alloy Enterprises (Burlington, MA)", "Role(s) Checked": "Co-op board (Thermal Design Engineer, Mechanical Engineer)", Reason: "2026-09-20: Only Fall 2026 and Spring 2026 (already past) co-op reqs found; no Spring 2027 posted yet." },
  { Company: "Commonwealth Fusion Systems (Devens, MA)", "Role(s) Checked": "jobs.lever.co/cfsenergy board directly", Reason: "2026-09-20: Zero internship/co-op postings currently listed (full-time reqs only). Previously-found Fall 2026 and Spring 2026 co-op listings are gone from the live board." },
  { Company: "GE Aerospace", "Role(s) Checked": "Engines Engineering Co-op (R5029619), Manufacturing Engineering Co-op (R5030077)", Reason: "2026-09-20 re-check: both confirmed dead ('no longer posted' / HTTP 410). Still no live Spring 2027 co-op found at Lynn or elsewhere — no change from prior run." },
  { Company: "Teradyne (North Reading, MA)", "Role(s) Checked": "Mechanical Engineering Co-op", Reason: "2026-09-20: Only a Spring 2026 (already past) cohort found; no Spring 2027 posted yet." },
  { Company: "Vicor (Andover, MA)", "Role(s) Checked": "Full careers site", Reason: "2026-09-20: No co-op/internship postings found for any season — full-time roles only." },
  { Company: "Hologic (Marlborough, MA)", "Role(s) Checked": "Co-Op, New Product Development Engineering; Software Eng Co-op; Automation Developer Co-op", Reason: "2026-09-20: Only Spring 2026 (already past) postings confirmed; the NPD Engineering co-op page returned HTTP 503 on two attempts — could not confirm season, excluded." },
  { Company: "iRobot (Bedford, MA)", "Role(s) Checked": "Full careers site", Reason: "2026-09-20: No current Spring 2027 postings found — only historical 2022 listings and older closed Workday reqs." },
  { Company: "Vicarious Surgical (Waltham, MA)", "Role(s) Checked": "Full careers site", Reason: "2026-09-20 re-check: no current Spring 2027 postings; most recent was a January 2026 Mechanical Engineering Co-Op (already past)." },
  { Company: "Apptronik / Figure AI / Agility Robotics", "Role(s) Checked": "Mechanical/hardware internship search", Reason: "2026-09-20: No Winter 2026/Spring 2027 mechanical postings found. One apparent lead (Figure AI 'Hardware Reliability Intern') turned out on direct fetch to be titled Summer 2026 and is closed/removed." },
  // --- Added 2026-09-20 ~06:57 UTC routine run ---
  { Company: "GE Aerospace", "Role(s) Checked": "Engines Eng Co-op R5029619 (dead), Manufacturing Eng Co-op R5030077 (HTTP 410), general Engines Eng Co-op — Lynn/Evendale (aggregator: EXPIRED), Lynn CNC Trainee Co-Op R5034331 (dead)", Reason: "2026-09-20 ~06:57 UTC re-check: all four known reqs confirmed dead ('no longer posted' / HTTP 410 / EXPIRED). No live Spring 2027 mechanical/manufacturing req found anywhere at GE Aerospace this pass." },
  { Company: "Analog Devices", "Role(s) Checked": "Spring/Fall mechanical co-op search", Reason: "2026-09-20 ~06:57 UTC: still not posted; search summary indicates Summer 2027/2028-wave postings expected ~Oct/Nov 2026. No change." },
  { Company: "Caterpillar", "Role(s) Checked": "r0000380501 '2027 Engineering Corporate Internship Program – Materials', r0000384650 '2027 Summer Corporate Intern – Engineering'", Reason: "2026-09-20 ~06:57 UTC: only Summer 2027 reqs found. No Winter 2026/Spring 2027 posting located." },
  { Company: "Olympus (Westborough, MA)", "Role(s) Checked": "Jan–June 2026 Manufacturing Engineering Co-Op (direct fetch); July–Dec 2026 co-op", Reason: "2026-09-20 ~06:57 UTC: Jan–June 2026 cohort directly confirmed 'no longer accepting applications'. July–Dec 2026 is wrong season (Fall, not Winter/Spring). No real URL found for a 'Jan–June 2027' version — a prior aggregator claim of one appears to be a synthesis artifact, not an actual posting. Ruling out fully pending a real link." },
  { Company: "Draper Laboratory", "Role(s) Checked": "JR002884 (Optics-Physics Sensor Eng Co-op, Spring 2027), JR002885 (Sensor Electrical Eng Co-op, Spring 2027), JR002767 (Mechanical Eng & System Packaging Intern), JR002688 (Acoustic and Vibration Technologies Co-op), JR002717 (Metrology Co-op)", Reason: "2026-09-20 ~06:57 UTC: JR002884/JR002885 wrong discipline (optics/electrical, consistent with prior exclusion). JR002767 is a Summer role per aggregator, not Winter/Spring. JR002688 and JR002717 are open/rolling but state no specific season/year on the posting — fail the 'season stated' bar, excluded pending a dated version." },
  { Company: "MIT Lincoln Laboratory (Lexington, MA)", "Role(s) Checked": "Group 07-71 Mechanical Engineering (Jan–June 2026), Group 07-76 Control & Autonomous Systems (Jan–June 2026), Group 07-77 (July–Dec 2026)", Reason: "2026-09-20 ~06:57 UTC: all three are past/wrong-season cycles relative to today. No new Spring 2027 (Jan–June 2027) mechanical/aerospace req found beyond the already-tracked Microfabrication Co-Op." },
  { Company: "Boston Dynamics (Waltham, MA)", "Role(s) Checked": "req R2495 'Mechanical Engineering Intern' (Atlas program)", Reason: "2026-09-20 ~06:57 UTC: search snippet mentions 'Spring 2027 Co-Op' but Workday fetch returned empty content twice — could not independently verify or confirm this is distinct from already-tracked req R2476. Worth a follow-up with better Workday access." },
  { Company: "Commonwealth Fusion Systems (Devens, MA)", "Role(s) Checked": "'Intern – Mechanical Engineer – Fall Co-op 2026'", Reason: "2026-09-20 ~06:57 UTC: title/season is Fall 2026 only, and the posting itself now 404s. No Spring 2027 version found." },
  { Company: "Relativity Space", "Role(s) Checked": "'2027 Mechanical Engineer Intern' reqs including a Boston, MA location", Reason: "2026-09-20 ~06:57 UTC: context strongly suggests Summer 2027 wave (aggregator states ~47% of new listings carry 'Summer 2027' in title); not confirmed as Winter 2026/Spring 2027 — excluded, but the Boston, MA listing specifically is worth a direct-fetch check next pass." },
  { Company: "Astranis", "Role(s) Checked": "'Mechanical Engineer Intern (Winter 2027)', SF, via Greenhouse", Reason: "2026-09-20 ~06:57 UTC: directly verified live and open ($29/hr) but season is literally 'Winter 2027' (not Winter 2026 or Spring 2027 as required) — excluded on strict season-match grounds. Near miss, worth flagging if Hamza wants to reconsider the season window." },
  { Company: "L3Harris", "Role(s) Checked": "'Mechanical Engineer Co-op' and 'Sustainment Mechanical Engineering Co-op' (Greenville, TX)", Reason: "2026-09-20 ~06:57 UTC: both confirmed dead (404) on direct fetch. Only software/AI Spring 2027 reqs remain live — discipline mismatch, consistent with prior exclusion." },
  { Company: "Curtiss-Wright", "Role(s) Checked": "JR1907 'Co-op (Spring Term)', Cheswick, PA", Reason: "2026-09-20 ~06:57 UTC: posting has no explicit year in the title; direct fetch blocked (403). Could not confirm Spring 2027 specifically — excluded pending verification, worth a re-check." },
  { Company: "Sierra Nevada Corporation", "Role(s) Checked": "Mechanical co-op/intern search", Reason: "2026-09-20 ~06:57 UTC: only found a historical (2023) mechanical co-op posting and current Summer 2027 reqs. No Winter 2026/Spring 2027 posting found." },
  { Company: "Redwire Space / Karman Space", "Role(s) Checked": "Mechanical/aerospace intern search", Reason: "2026-09-20 ~06:57 UTC: candidate roles exist at both but could not verify season (Redwire rate-limited 429; Karman fetch didn't surface target content). Excluded, worth re-checking with more time/attempts." },
  { Company: "Joby Aviation / Honeywell Aerospace / Moog / Woodward / Firefly Aerospace / Impulse Space / Virgin Galactic / Vecna Robotics / Desktop Metal / Markforged / Boston Dynamics AI Institute", "Role(s) Checked": "Mechanical/aerospace/systems/manufacturing/robotics internship search", Reason: "2026-09-20 ~06:57 UTC: no Winter 2026/Spring 2027 postings found at any of these — only Summer 2027, Fall 2026, or undated rolling reqs turned up." },
  { Company: "General Dynamics Electric Boat (Groton, CT)", "Role(s) Checked": "req 601496955 (already Partial in `rows`), including a text-proxy (r.jina.ai) fetch workaround", Reason: "2026-09-20 ~06:57 UTC: still blocked by Cloudflare on jobs.buildsubmarines.com even via proxy workaround. WebSearch snippets remain consistent with the tracked posting (title, Groton CT, mechanical/aerospace-eligible, US citizenship required) but no independent direct-fetch confirmation obtained — status in `rows` unchanged at Partial." },
  // --- Added 2026-09-20 ~13:00 UTC routine run ---
  { Company: "General Dynamics Electric Boat (Groton, CT)", "Role(s) Checked": "req 601496955 (already Partial in `rows`) — 4th consecutive re-check", Reason: "2026-09-20 ~13:00 UTC: still blocked by Cloudflare on jobs.buildsubmarines.com (4th consecutive failed direct-fetch attempt). WebSearch corroborates the exact tracked title ('2027 Spring Engineering CO-OP Trainee') still appears on the aggregator's own listing — no new information; status in `rows` unchanged at Partial. Deprioritizing further automated attempts after 4 straight blocks — would need an actual in-browser check to resolve." },
  { Company: "Boston Dynamics (Waltham, MA)", "Role(s) Checked": "req R2495 'Mechanical Engineering Intern' (Atlas program) — re-check", Reason: "2026-09-20 ~13:00 UTC: Workday fetch still returns empty (3rd failed attempt across runs). A search-synthesis claim of 'Spring 2027, Jan–Aug 2027' could not be corroborated as a literal quote from any retrievable source this run — season still unconfirmed, not added to `rows`. Distinct req from already-tracked R2476 (same location/program). Also found and ruled out an unrelated same-titled Boston Dynamics posting that is explicitly Summer 2026 and inactive — a naming collision, not R2495." },
  { Company: "Relativity Space", "Role(s) Checked": "Boston, MA-flagged listing", Reason: "2026-09-20 ~13:00 UTC: careers page now shows only Cape Canaveral, FL and Stennis, MS roles — no Boston, MA listing currently live. Excluded — appears no longer posted." },
  { Company: "Curtiss-Wright", "Role(s) Checked": "JR1907 'Co-op (Spring Term)', Cheswick, PA", Reason: "2026-09-20 ~13:00 UTC: confirmed live via a zapply.jobs mirror (posted 2026-08-05), but the posting itself still states no year for 'Spring Term' — season is only an inference from posting date/cadence, not a stated fact, so it fails the verification bar. Excluded pending an explicitly dated version." },
  { Company: "Redwire Space", "Role(s) Checked": "'Mechanical Engineering Intern - Year Round' plus current Summer 2026 postings (Georgetown, IN; Goleta, CA)", Reason: "2026-09-20 ~13:00 UTC: only Summer 2026-dated postings and an undated 'year round' listing found — no Winter 2026/Spring 2027-specific posting located. Excluded on season grounds." },
  { Company: "Karman Space & Defense", "Role(s) Checked": "Internship program (general)", Reason: "2026-09-20 ~13:00 UTC: company's own internship page states the program is annual with an April 30 application deadline and positions running May/June–Aug/Sept — a summer-only program by design. Excluded — no Winter 2026/Spring 2027 track exists." },
  { Company: "Draper Laboratory", "Role(s) Checked": "JR002688 (Acoustic and Vibration Technologies Co-op), JR002717 (Metrology Co-op) — re-check", Reason: "2026-09-20 ~13:00 UTC: both re-confirmed open/rolling (JR002717 posted 2026-08-05, JR002688 posted ~1 month ago) but still carry no explicit season/year on the posting — no change from last check. Excluded pending a dated version." },
  { Company: "Analog Devices", "Role(s) Checked": "Mechanical co-op search — re-check", Reason: "2026-09-20 ~13:00 UTC: only a closed/past Jan–June 2025 Burlington, MA co-op found; no current Winter 2026/Spring 2027 posting — no change from prior finding." },
  { Company: "Caterpillar", "Role(s) Checked": "r0000290709 (now 404; prior title showed 'Spring/Summer 2026' — wrong season regardless); '2027 Engineering Corporate Parallel Co-op Program' (Tucson/Green Valley AZ, Champaign/Decatur/Mossville IL, Lafayette IN)", Reason: "2026-09-20 ~13:00 UTC: the previously-flagged req is dead and was wrong-season anyway. The 2027 Parallel Co-op Program has an ambiguous, continuous summer-plus-school-year structure (not a discrete Winter/Spring term) and no MA location — excluded as not a clean fit." },
  { Company: "Toyota Research Institute", "Role(s) Checked": "Live Lever board (jobs.lever.co/tri): Human Interactive Driving Intern (Fall 2026), Human-Centered AI Research Intern (Winter 2027), Robotics Research Intern - Post-Training (Spring 2027)", Reason: "2026-09-20 ~13:00 UTC: all current postings are ML/AI research roles (not mechanical engineering) located in Los Altos, CA (not Cambridge, MA). Excluded — discipline and location mismatch." },
  { Company: "Waters Corporation / Instron / Analogic / Boston Metal / Charles River Laboratories", "Role(s) Checked": "General mechanical/manufacturing co-op search, each company", Reason: "2026-09-20 ~13:00 UTC: no current mechanical/manufacturing internship or co-op postings found for any season at any of these MA-area employers (Charles River's most comparable posting, a Facilities Engineer Intern, is a closed 2025 Summer role)." },
  { Company: "Bose", "Role(s) Checked": "Mechanical Engineer Co-op / Concept Prototyping (req R25833), Advanced Manufacturing Mechanical Engineering Intern", Reason: "2026-09-20 ~13:00 UTC: only LinkedIn mirrors found, both appearing to be stale reqs from a prior cycle; the specific aggregator mirror link 404'd and Bose's own careers URL 404'd. Excluded — could not confirm any currently-open, correctly-seasoned posting." },
  { Company: "Thermo Fisher Scientific", "Role(s) Checked": "Manufacturing Engineering Intern (Bedford, MA); Manufacturing Engineering Co-op (Marietta, OH)", Reason: "2026-09-20 ~13:00 UTC: Bedford, MA role's stated start dates (May 24/June 14, 2027) put it in the Summer 2027 wave — wrong season. Marietta, OH role is not in MA and its season couldn't be confirmed. Excluded." },
  { Company: "Philips", "Role(s) Checked": "EMC Engineer Co-op, Hardware Test/Reliability Co-op (Andover, MA)", Reason: "2026-09-20 ~13:00 UTC: only Jan–June 2025 (already past) postings found; no current 2026/2027 posting surfaced. Excluded." },
  { Company: "Hexagon Manufacturing Intelligence / Oshkosh Corporation / Terex Corporation / Polaris Industries / Waymo", "Role(s) Checked": "General mechanical engineering intern/co-op search, each company", Reason: "2026-09-20 ~13:00 UTC: all confirmed to run Summer-only internship cycles (Summer 2026 or Summer 2027 postings found, no Winter 2026/Spring 2027 track) — excluded on season grounds." },
  { Company: "Sublime Systems (Somerville, MA)", "Role(s) Checked": "Company Lever board (jobs.lever.co)", Reason: "2026-09-20 ~13:00 UTC: board directly confirmed to state 'No job postings currently open.' Excluded." },
  { Company: "Lam Research", "Role(s) Checked": "2027 mechanical engineering intern cycle", Reason: "2026-09-20 ~13:00 UTC: per the company's own careers-program messaging, the 2027 cycle has not yet been posted as of mid-September 2026. Not yet open — worth re-checking in a few weeks." },
  { Company: "Textron Systems (Wilmington, MA)", "Role(s) Checked": "'2027 Intern - Materials Quality Engineer (Weapons)'", Reason: "2026-09-20 ~13:00 UTC: role title found (materials discipline, in-scope) but the Taleo posting page returned only template placeholders with no real content on fetch — could not confirm season, pay, or open status. Unresolved, not added — worth a direct follow-up check." },
  { Company: "Aurora Flight Sciences (Boeing subsidiary)", "Role(s) Checked": "General internships page, Manufacturing Engineering Intern mention", Reason: "2026-09-20 ~13:00 UTC: company materials describe MA-based (and VA-based) autonomy/mechanical engineering work, but no specific dated 2027 co-op listing could be found — only a generic description with no season stated in the retrievable snippet. Unresolved — worth a direct check of careers.aurora.aero." },
  { Company: "GE HealthCare", "Role(s) Checked": "'LSS Mechanical Engineering Co-op' (title found via zapply)", Reason: "2026-09-20 ~13:00 UTC: a zapply search snippet surfaced this title but the actual page returned unrelated listings on two fetch attempts — could not verify season, location, or open status. Unresolved — needs a more targeted follow-up (e.g. direct careers.gehealthcare.com search)." },
  { Company: "RTX (Collins Aerospace)", "Role(s) Checked": "Mechanical Engineering Co-op (Winter/Spring 2027), Cedar Rapids IA, req 01869080", Reason: "2026-09-20 ~13:00 UTC: dedupe check — this req ID is identical to the RTX Cedar Rapids IA row already tracked in `rows`. Not a new posting; not re-added." },
  // --- Added 2026-09-20 ~19:00 UTC routine run ---
  { Company: "Boston Dynamics (Waltham, MA)", "Role(s) Checked": "Mechanical Engineering Co-Op (req R2476, previously tracked in `rows` as Partial)", Reason: "2026-09-20: queried Boston Dynamics' live Workday CXS jobs API directly for all open reqs — all 37 current postings are workerSubType 'Regular'; zero Intern/Co-Op postings exist company-wide right now. R2476 is no longer live. MOVED from `rows` to `checked`." },
  { Company: "Insulet", "Role(s) Checked": "Co-op, Next Gen Platforms (NGP) Systems Engineering: January-June 2027 (Onsite), req REQ-2026-18071", Reason: "2026-09-20: title/season/pay/location corroborated by two independent aggregator mirrors (Zapply, Workopia) and the live Workday jobs-search API, but no source yielded a verifiable canonical Insulet Workday deep-link URL (unlike its sibling Insulet Acton reqs) — not added without a working link. Note: a separate, distinct 'NGP Systems Engineering Co-op (July-Dec 2026)' req also exists at Insulet but is wrong season, not this one. Worth a direct re-check next run." },
  { Company: "Draper Laboratory", "Role(s) Checked": "Sensor Electrical Engineering Co-op (Spring 2027), JR002885", Reason: "2026-09-20: re-confirmed live via direct Workday API fetch (posted 20 days ago) but still excluded — electrical/sensor discipline, outside Hamza's target list. No change from prior exclusion (see JR002884/JR002885 entry above)." },
  { Company: "Textron Systems (Wilmington, MA)", "Role(s) Checked": "'2027 Intern - Materials Quality Engineer (Weapons)', req 1539632 / job 342556", Reason: "2026-09-20: Taleo page now returns real content (progress from prior runs' template-placeholder blocker) — confirmed Wilmington MA, Full-time Internship/Co-Op type, posted 09/01/2026, requires US Citizenship for classified access. But the posting itself still never states a season (no 'Winter 2026'/'Spring 2027' wording anywhere) — fails the season-verification bar, not added." },
  { Company: "Aurora Flight Sciences (Boeing subsidiary)", "Role(s) Checked": "careers.aurora.aero direct search", Reason: "2026-09-20: site is a fully client-side-rendered Taleo CWS v2 board — direct fetch returns only an empty JS shell with no embedded job data. WebSearch found no specific dated Spring 2027 mechanical/co-op requisition. Still unverifiable." },
  { Company: "GE HealthCare", "Role(s) Checked": "'LSS Mechanical Engineering Co-op', req R4046267-1, Madison WI", Reason: "2026-09-20: fetched full description directly — contains zero season/date/year language anywhere in the posting, and location is Madison WI (not Boston area). Excluded for failing the season-verification bar. (A separate, distinct GE HealthCare req — 'Infant Care V&V Engineering Co-op - Spring 2027,' Waukesha WI — DID state its season and was added to `rows`.)" },
  { Company: "MKS Instruments (Andover, MA)", "Role(s) Checked": "Workday university-recruiting API query for 'Mechanical Co-op' + Andover", Reason: "2026-09-20: zero matching results — their only 4 open student-program reqs are in Milpitas CA, Beaverton OR, Malaysia, and Thailand. A 'Spring 2027' reference in initial search snippets appears to be a stale aggregator artifact, not a live Andover MA posting." },
  { Company: "Lam Research", "Role(s) Checked": "2027 mechanical/materials/process engineering intern cycle", Reason: "2026-09-20: confirmed all 2026-cycle reqs (incl. mechanical) closed by mid-May 2026; no 2027-cycle reqs posted yet. No change from prior run." },
  { Company: "Analog Devices / Caterpillar / Commonwealth Fusion Systems", "Role(s) Checked": "Quick re-check for newly-opened Spring 2027 cycles", Reason: "2026-09-20: no change from prior findings — Analog Devices' Spring 2027 cycle not yet posted; Caterpillar's 2027 programs remain ambiguous multi-rotation structures with no MA location; Commonwealth Fusion Systems has only a Fall 2026 co-op and general internship postings, no Spring 2027 mechanical req." },
  { Company: "Westinghouse Electric", "Role(s) Checked": "General mechanical/nuclear intern search", Reason: "2026-09-20: only Summer 2027 mechanical engineering internships found (Rock Hill/Columbia, SC); no Spring 2027 co-op located." },
  { Company: "NuScale Power", "Role(s) Checked": "General mechanical/nuclear intern search", Reason: "2026-09-20: no Spring 2027-specific posting found; only a general, undated internship program description (Corvallis OR / Houston TX / remote)." },
  { Company: "Intuitive Surgical", "Role(s) Checked": "General mechanical intern search", Reason: "2026-09-20: only Summer 2027 (May-Aug) internships found in Sunnyvale, CA; no Spring 2027 co-op." },
  { Company: "Stryker", "Role(s) Checked": "General mechanical intern search", Reason: "2026-09-20: only Summer 2027 mechanical engineering internships found (NJ/CA/MI); no Spring 2027 co-op located." },
  { Company: "Kratos Defense", "Role(s) Checked": "Co-op program rotation search", Reason: "2026-09-20: co-op program uses a multi-semester rotation (Summer 2025 -> Spring 2026 -> Fall 2026 cohort cited); no new Spring 2027 rotation/cohort found posted yet." },
  { Company: "HII / Newport News Shipbuilding", "Role(s) Checked": "General co-op/intern search", Reason: "2026-09-20: only 2027 Summer internships found; per HII's own program description, Spring co-op postings typically open 'September through October' — nothing live yet for Spring 2027 specifically. Worth re-checking in ~2-4 weeks." },
  { Company: "Parsons Corporation", "Role(s) Checked": "Structural Engineer Intern / Engineering Internship-Co-Op search", Reason: "2026-09-20: all postings found are Summer 2027; no Spring 2027 structural/mechanical posting located." },
  { Company: "Realtime Robotics (Boston, MA)", "Role(s) Checked": "General intern/co-op search", Reason: "2026-09-20: no internship/co-op postings of any season found." },
  { Company: "Piaggio Fast Forward (Boston, MA)", "Role(s) Checked": "Greenhouse job board, direct fetch", Reason: "2026-09-20: only 4 open roles today (Mechanical Engineering Machinist, IT Specialist, part-time Office Manager, Business Development Leader) — none are co-op/intern, none carry season/date info. A 'Robotics and AI Co-op' listing found via search appears stale/closed." },
  { Company: "Diligent Robotics", "Role(s) Checked": "General intern/co-op search", Reason: "2026-09-20: only an unrelated Austin, TX mechanical engineering intern reference found, no 2027/season confirmation, no Boston presence." },
  { Company: "Veo Robotics", "Role(s) Checked": "General intern/co-op search", Reason: "2026-09-20: no 2027-specific posting found; general hardware/mechanical engineering intern role description only, no season stated." },
  { Company: "Coherent / II-VI", "Role(s) Checked": "General mechanical co-op search", Reason: "2026-09-20: no Spring 2027 mechanical co-op posting found specific to this company." },
  { Company: "Fisker / Canoo / Nikola / VinFast / Karma Automotive", "Role(s) Checked": "General intern/co-op search", Reason: "2026-09-20: no active internship/co-op postings found at any of these; several (Fisker, Canoo, Nikola) have known bankruptcy/financial-distress history that likely explains absent active recruiting." },
];
const wsChecked = xlsx.utils.json_to_sheet(checked);
wsChecked["!cols"] = [{ wch: 34 }, { wch: 55 }, { wch: 70 }];

const ws = xlsx.utils.json_to_sheet(rows);
ws["!cols"] = [
  { wch: 26 }, // Company
  { wch: 46 }, // Role Title
  { wch: 34 }, // Discipline
  { wch: 26 }, // Season
  { wch: 22 }, // Location
  { wch: 14 }, // Distance
  { wch: 40 }, // Pay
  { wch: 60 }, // Link
  { wch: 55 }, // Link Verified
  { wch: 50 }, // Notes
];

const wb = xlsx.utils.book_new();
xlsx.utils.book_append_sheet(wb, ws, "Winter26-Spring27 Internships");
xlsx.utils.book_append_sheet(wb, wsChecked, "Checked - Not Included");
xlsx.writeFile(wb, "Engineering-Internships-Winter2026-Spring2027.xlsx");
console.log("done");
