import xlsx from "xlsx";

// Distances are straight-line (great-circle) approximations from Boston, MA,
// for quick sorting/reference only — not driving distance.
const rows = [
  {
    Company: "ASM (ASM International)",
    "Role Title": "Manufacturing Engineering Intern",
    Discipline: "Manufacturing Engineering",
    Season: "Spring 2027 (Jan/Feb–Apr/May)",
    Location: "Greater Phoenix, AZ",
    "Distance from Boston, MA (mi, approx.)": 2300,
    Pay: "Not stated on posting",
    "Application Link": "https://www.asm.com/open-vacancies/manufacturing-engineering-intern-spring-2027-4830098101?gh_jid=4830098101",
    "Link Verified": "Yes — fetched directly, page live, Apply button present",
    Notes: "12 weeks, full-time, on-site. Enrolled full-time student required.",
  },
  {
    Company: "ASM (ASM International)",
    "Role Title": "Mechanical Engineering Intern",
    Discipline: "Mechanical Engineering",
    Season: "Spring 2027 (Jan/Feb–Apr/May)",
    Location: "Greater Phoenix, AZ",
    "Distance from Boston, MA (mi, approx.)": 2300,
    Pay: "Not stated on posting",
    "Application Link": "https://www.asm.com/open-vacancies/mechanical-engineering-intern-spring-2027-4830929101?gh_jid=4830929101",
    "Link Verified": "Yes — fetched directly, page live, Apply button present",
    Notes: "12 weeks, full-time, on-site. Enrolled full-time student required.",
  },
  {
    Company: "Varda Space Industries",
    "Role Title": "Manufacturing Engineering Internship",
    Discipline: "Manufacturing Engineering",
    Season: "Spring 2027 (Jan–May)",
    Location: "El Segundo, CA",
    "Distance from Boston, MA (mi, approx.)": 2600,
    Pay: "Not stated on posting",
    "Application Link": "https://job-boards.greenhouse.io/vardaspace/jobs/7824767003",
    "Link Verified": "Yes — fetched directly, page live, Apply button present",
    Notes: "Full-time, on-site. Must be enrolled undergrad/grad.",
  },
  {
    Company: "Formlabs",
    "Role Title": "Mechanical Engineering Intern",
    Discipline: "Mechanical Engineering",
    Season: "Winter/Spring 2027 (Jan–Apr)",
    Location: "Somerville, MA",
    "Distance from Boston, MA (mi, approx.)": 3,
    Pay: "Not stated on posting",
    "Application Link": "https://careers.formlabs.com/job/8130829/apply/?gh_jid=8130829&gh_src=lrhd6k1",
    "Link Verified": "Yes — fetched directly, page live",
    Notes: "Right in the Boston metro. Portfolio of prior engineering work requested.",
  },
  {
    Company: "Blue Origin",
    "Role Title": "Spring 2027 Aerospace Systems Engineering Intern – Graduate",
    Discipline: "Aerospace / Systems Engineering",
    Season: "Spring 2027 (Jan–Apr, ~15 wks)",
    Location: "Greater Seattle Area, WA",
    "Distance from Boston, MA (mi, approx.)": 2490,
    Pay: "Not stated on posting",
    "Application Link": "https://blueorigin.wd5.myworkdayjobs.com/BlueOrigin/job/Greater-Seattle-Area/Spring-2027-Aerospace-Systems-Engineering-Intern---Graduate_R66202/apply",
    "Link Verified": "Partial — official Blue Origin/Workday domain, title confirms season via direct search, but the page is JS-rendered and blocked automated fetch (403/empty). Open a browser to confirm before applying.",
    Notes: "US citizen/national/permanent resident required (ITAR).",
  },
  {
    Company: "Blue Origin",
    "Role Title": "Spring 2027 Aerospace Systems Engineering Internship – Undergraduate",
    Discipline: "Aerospace / Systems Engineering",
    Season: "Spring 2027 (Jan–Apr, ~15 wks)",
    Location: "Greater Seattle Area, WA",
    "Distance from Boston, MA (mi, approx.)": 2490,
    Pay: "Not stated on posting",
    "Application Link": "https://blueorigin.wd5.myworkdayjobs.com/BlueOrigin/job/Greater-Seattle-Area/Spring-2027-Aerospace-Systems-Engineering-Internship----Undergraduate_R66207/apply",
    "Link Verified": "Partial — same as above (Workday page blocked automated fetch). Verify live in-browser before applying.",
    Notes: "US citizen/national/permanent resident required (ITAR). Sophomore standing+.",
  },
  {
    Company: "Blue Origin",
    "Role Title": "Spring 2027 Structural & Mechanical Engineering Internship – Undergraduate",
    Discipline: "Structural / Mechanical Engineering",
    Season: "Spring 2027",
    Location: "Not specified on posting",
    "Distance from Boston, MA (mi, approx.)": null,
    Pay: "Not stated on posting",
    "Application Link": "https://blueorigin.wd5.myworkdayjobs.com/en-US/BlueOrigin/job/Spring-2027-Structural---Mechanical-Engineering-Internship---Undergraduate_R66356",
    "Link Verified": "Partial — official Workday domain, blocked automated fetch. Verify live in-browser before applying.",
    Notes: "US citizen/national/permanent resident required (ITAR).",
  },
  {
    Company: "Blue Origin",
    "Role Title": "Spring 2027 Structural & Mechanical Systems Engineering Internship – Graduate",
    Discipline: "Structural / Mechanical Systems Engineering",
    Season: "Spring 2027 (~15 wks)",
    Location: "Los Angeles, CA",
    "Distance from Boston, MA (mi, approx.)": 2600,
    Pay: "Not stated on posting",
    "Application Link": "https://www.ziprecruiter.com/c/Blue-Origin/Job/Spring-2027-Structural-&-Mechanical-Systems-Engineering-Internship-Graduate/-in-Los-Angeles,CA?jid=67aec7854122d860",
    "Link Verified": "Partial — this is a ZipRecruiter mirror of the Blue Origin listing (couldn't locate the direct Workday URL). Confirm on blueorigin.com/careers before applying.",
    Notes: "Grad student, US citizen/national/permanent resident required (ITAR).",
  },
  {
    Company: "Blue Origin",
    "Role Title": "Spring 2027 Engineering Intern – Undergraduate",
    Discipline: "General Engineering (unspecified sub-discipline)",
    Season: "Spring 2027",
    Location: "Not specified on posting",
    "Distance from Boston, MA (mi, approx.)": null,
    Pay: "Not stated on posting",
    "Application Link": "https://blueorigin.wd5.myworkdayjobs.com/en-US/BlueOrigin/job/Spring-2027--Engineering-Intern---Undergraduate_R69064",
    "Link Verified": "Partial — official Workday domain, blocked automated fetch. Verify live in-browser before applying.",
    Notes: "US citizen/national/permanent resident required (ITAR).",
  },
  {
    Company: "Tesla",
    "Role Title": "Internship, Manufacturing Engineering, Optimus",
    Discipline: "Manufacturing Engineering",
    Season: "Winter/Spring 2027 (Jan–May)",
    Location: "Fremont, CA",
    "Distance from Boston, MA (mi, approx.)": 2700,
    Pay: "$20–$50/hr (Tesla's general posted internship pay band; not role-specific)",
    "Application Link": "https://www.tesla.com/careers/search/job/internship-manufacturing-engineering-optimus-winter-spring-2027-279034",
    "Link Verified": "Partial — official tesla.com domain, blocked automated fetch (403, bot protection). Verify live in-browser before applying.",
    Notes: "Min. 12 weeks, full-time, on-site.",
  },
  {
    Company: "Tesla",
    "Role Title": "Internship, Industrial Engineer, Manufacturing",
    Discipline: "Industrial Engineering",
    Season: "Winter/Spring 2027 (Jan–May)",
    Location: "Fremont, CA",
    "Distance from Boston, MA (mi, approx.)": 2700,
    Pay: "$20–$50/hr (Tesla's general posted internship pay band; not role-specific)",
    "Application Link": "https://www.tesla.com/careers/job/246725",
    "Link Verified": "Partial — official tesla.com domain, blocked automated fetch (403, bot protection). Verify live in-browser before applying.",
    Notes: "Min. 12 weeks, full-time, on-site.",
  },
  {
    Company: "Hendrick Motorsports",
    "Role Title": "Design Engineering Intern",
    Discipline: "Mechanical / Automotive Design Engineering",
    Season: "Spring/Summer 2027 (6–9 month assignment starting spring)",
    Location: "Charlotte, NC",
    "Distance from Boston, MA (mi, approx.)": 845,
    Pay: "Not stated on posting",
    "Application Link": "https://hendrick.wd5.myworkdayjobs.com/en-US/HMSCareers/job/Design-Engineering-Intern--Spring-Summer-2027-_R-80377",
    "Link Verified": "Partial — official Workday domain, blocked automated fetch. Verify live in-browser before applying.",
    Notes: "NASCAR team — structural/CAD design internship. Min GPA 2.8, 30+ semester hrs completed.",
  },
  {
    Company: "General Dynamics Mission Systems",
    "Role Title": "Infrastructure Engineer Co-op",
    Discipline: "Systems / Infrastructure Engineering",
    Season: "Fall 2026 or Spring 2027",
    Location: "Pittsfield, MA",
    "Distance from Boston, MA (mi, approx.)": 135,
    Pay: "Not stated on posting",
    "Application Link": "https://www.gd.com/careers/infrastructure-engineer-co-op-fall-2026-or-spring-2027-pittsfield-ma-us-2026-72403-gdms-opportunity",
    "Link Verified": "Partial — official gd.com domain, blocked automated fetch (403). Verify live in-browser before applying.",
    Notes: "Closest option to Boston besides Formlabs. Likely requires US citizenship (ITAR/clearance).",
  },
  {
    Company: "Boeing (South Carolina)",
    "Role Title": "2026 Specialty Program – BSC Co-op – Engineering Internship Program (Materials & Process Eng, Industrial Eng)",
    Discipline: "Materials/Process Engineering, Industrial Engineering",
    Season: "Fall 2026–Spring 2027 (6-month co-op)",
    Location: "North Charleston, SC (Boeing SC site)",
    "Distance from Boston, MA (mi, approx.)": 850,
    Pay: "Not stated on posting",
    "Application Link": "https://boeing.wd1.myworkdayjobs.com/en-US/INTERN/job/XMLNAME-2026-Specialty-Program---BSC-Co-op---Engineering-Internship-Program_JR2026491626",
    "Link Verified": "Partial — official Boeing/Workday domain, title/search snippet confirms Fall 2026–Spring 2027 span, but page is JS-rendered and blocked automated fetch. Verify live in-browser before applying.",
    Notes: "6-month co-op spanning into Spring 2027.",
  },
  {
    Company: "Boeing",
    "Role Title": "Drexel Internship Fall Co-op 2026 – Engineering (Software, Industrial, Manufacturing, Reliability/Maintainability, Systems, Mechanical Systems, Structures, Wire Install/Design)",
    Discipline: "Systems / Mechanical Systems / Structures / Manufacturing Engineering",
    Season: "Fall 2026–Spring 2027 (6-month co-op)",
    Location: "Not specified on posting (Drexel University co-op partnership — site varies by team)",
    "Distance from Boston, MA (mi, approx.)": null,
    Pay: "Not stated on posting",
    "Application Link": "https://boeing.wd1.myworkdayjobs.com/en-US/INTERN/job/Drexel-Internship-Fall-Co-op-2026---Engineering_JR2026515142",
    "Link Verified": "Partial — official Boeing/Workday domain, title/search snippet confirms Fall 2026–Spring 2027 span, but page is JS-rendered and blocked automated fetch. Verify live in-browser before applying.",
    Notes: "Restricted to Drexel University co-op program students — check eligibility before applying.",
  },
  {
    Company: "John Deere",
    "Role Title": "Part-Time Student – Factory Engineering",
    Discipline: "Manufacturing / Factory Engineering",
    Season: "Year-round part-time during school year (covers Winter 2026 & Spring 2027)",
    Location: "East Moline, IL",
    "Distance from Boston, MA (mi, approx.)": 980,
    Pay: "Not stated on posting",
    "Application Link": "https://careers.deere.com/careers/job/137468659226-part-time-student-factory-engineering-east-moline-il-east-moline-illinois-united-states?domain=johndeere.com",
    "Link Verified": "Partial — official careers.deere.com domain, page structure confirmed real but automated fetch couldn't render full listing text. Verify live in-browser before applying.",
    Notes: "16–20 hrs/wk during school year, 30–40 hrs/wk in summer. Requires graduation Dec 2026 or later. CMM/dimensional-analysis work in production environment.",
  },
  {
    Company: "GE Vernova (Nuclear)",
    "Role Title": "Nuclear Engineering Co-Op/Intern",
    Discipline: "Nuclear / Mechanical / Chemical / Electrical / Materials / Controls / Civil-Structural Engineering",
    Season: "Spring 2027",
    Location: "Wilmington, NC",
    "Distance from Boston, MA (mi, approx.)": 720,
    Pay: "$1,000–$2,000/week (varies by degree level)",
    "Application Link": "https://careers.gevernova.com/ge-vernova-nuclear-engineering-co-op-intern-spring-2027/job/R5048552",
    "Link Verified": "Yes — fetched directly, confirmed OPEN, posted Aug 7, 2026 (within freshness window)",
    Notes: "Housing/relocation assistance if 50+ mi from site. Must be work-authorized without sponsorship.",
  },
  {
    Company: "GE Vernova (Nuclear)",
    "Role Title": "Nuclear – Field Services Spring Internship",
    Discipline: "Engineering / Engineering Technology",
    Season: "Spring 2027 (starts January 2027)",
    Location: "Wilmington, NC (up to 70% travel to nuclear plant sites)",
    "Distance from Boston, MA (mi, approx.)": 720,
    Pay: "$1,000–$2,000/week (varies by experience)",
    "Application Link": "https://careers.gevernova.com/ge-vernova-nuclear-field-services-spring-internship-2027/job/R5049161",
    "Link Verified": "Yes — fetched directly, confirmed OPEN, posted Aug 7, 2026 (within freshness window)",
    Notes: "Housing/relocation assistance if 50+ mi from site. Must be work-authorized without sponsorship.",
  },
  {
    Company: "NASA (Pathways Internship Program)",
    "Role Title": "Pathways Internship – various engineering disciplines",
    Discipline: "Mechanical / Systems / Aerospace (varies by center & opening)",
    Season: "Spring 2027 (apply via USAJOBS; deadline Sept 14, 2026)",
    Location: "Varies — multiple NASA centers nationwide",
    "Distance from Boston, MA (mi, approx.)": null,
    Pay: "Federal student stipend scale, varies by degree level (not a fixed rate)",
    "Application Link": "https://www.usajobs.gov/",
    "Link Verified": "Yes — usajobs.gov is the live, official application portal (this is a program, not a single job req — search USAJOBS for open NASA Pathways postings)",
    Notes: "US citizenship required. Cumulative GPA 2.9+ required. Spring 2027 window opens on USAJOBS in fall 2026.",
  },
];

const checked = [
  { Company: "BWX Technologies (Euclid, OH)", "Role(s) Checked": "Materials Engineering Intern/Co-Op; Manufacturing Engineer Intern/Co-Op", Reason: "Both confirmed FILLED when opened directly (checked Aug 21, 2026)" },
  { Company: "Symbotic (Wilmington, MA)", "Role(s) Checked": "Systems Engineer Co-Op; Machine Learning Intern; Hardware Engineer Intern", Reason: "All specific req links 404'd; live careers page currently shows zero intern/co-op postings, only New Grad roles (checked Aug 21, 2026)" },
  { Company: "Amazon Robotics (Westborough, MA)", "Role(s) Checked": "Industrial Engineer Intern/Co-op; Process Engineer Intern/Co-op", Reason: "Specific job IDs found via search returned 404 (expired/removed) when opened directly" },
  { Company: "Cummins (Columbus, IN)", "Role(s) Checked": "Product Engineering; Materials Science & Engineering; Systems Reliability Engineering Co-Op", Reason: "Cummins.jobs is a JS-rendered SPA — could not confirm season or open status via automated fetch; not included without verification" },
  { Company: "Textron Aviation", "Role(s) Checked": "Spring Co-Op – Electronics Modules Engineer", Reason: "Could not confirm which year (2026 vs 2027) the listing covers; careers.textron.com blocked automated verification" },
  { Company: "GD Electric Boat", "Role(s) Checked": "Engineering Co-Op Trainee", Reason: "Only found a 'Spring 2026' cohort posting (already past) — Spring 2027 cycle not yet posted as of search date" },
  { Company: "Tesla / SpaceX / Apple / Google / Meta / Amazon Lab126 / NVIDIA", "Role(s) Checked": "Various hardware/mechanical searches", Reason: "No Winter 2026/Spring 2027-specific postings found for these disciplines (their volume is overwhelmingly Summer 2027); Apple's 'Hardware Undergrad Engineering' reqs appear evergreen with no season stated" },
  { Company: "GE Aerospace", "Role(s) Checked": "Manufacturing Engineering Co-op Spring 2027 (x2 reqs); Engines Engineering Co-op Spring 2027; Lynn, MA CNC Trainee Co-Op", Reason: "All 4 specific Spring 2027 reqs found via search had already closed ('no longer posted') when opened directly — this employer's Spring cohort appears to cycle very fast. Worth re-checking careers.geaerospace.com periodically for new Spring 2027 reqs." },
  { Company: "RTX / Raytheon / Collins Aerospace / Pratt & Whitney", "Role(s) Checked": "Spring 2027 co-op search on careers.rtx.com", Reason: "careers.rtx.com search endpoint blocked automated fetch (403); found one Raytheon 'Systems Engineer Co-op (Remote)' but it targets a Summer 2026 start, not Winter 2026/Spring 2027 — excluded on season grounds" },
  { Company: "Anduril Industries", "Role(s) Checked": "2027 Mechanical Engineer Intern; 2027 Manufacturing Engineer Intern (Boston, MA location available)", Reason: "Confirmed Summer 2027 only, not Winter/Spring — excluded on season grounds despite the attractive Boston location" },
  { Company: "Draper Laboratory (Cambridge, MA)", "Role(s) Checked": "Current-openings portal (redirects to Workday)", Reason: "Draper's own site confirms co-ops run fall/spring, but the live openings portal is a JS-rendered Workday page that blocked automated fetch — no specific Spring 2027 req could be confirmed. Worth checking manually (this would be a very close Boston option)." },
  { Company: "MIT Lincoln Laboratory (Lexington, MA)", "Role(s) Checked": "careers.ll.mit.edu search", Reason: "Only Summer 2026 reqs found (e.g. Mechanical/Optical Engineering SRP Intern) — no Spring 2027-specific postings live yet as of search date. Also close to Boston if it opens later." },
  { Company: "Lockheed Martin", "Role(s) Checked": "lockheedmartinjobs.com search for 'Spring 2027'", Reason: "Only found Spring 2026 co-ops (already past); direct search-jobs URL 404'd on retry — no confirmed Spring 2027 req found this session" },
];
const wsChecked = xlsx.utils.json_to_sheet(checked);
wsChecked["!cols"] = [{ wch: 34 }, { wch: 55 }, { wch: 70 }];

const ws = xlsx.utils.json_to_sheet(rows);
ws["!cols"] = [
  { wch: 26 }, // Company
  { wch: 46 }, // Role Title
  { wch: 34 }, // Discipline
  { wch: 26 }, // Season
  { wch: 22 }, // Location
  { wch: 14 }, // Distance
  { wch: 40 }, // Pay
  { wch: 60 }, // Link
  { wch: 55 }, // Link Verified
  { wch: 50 }, // Notes
];

const wb = xlsx.utils.book_new();
xlsx.utils.book_append_sheet(wb, ws, "Winter26-Spring27 Internships");
xlsx.utils.book_append_sheet(wb, wsChecked, "Checked - Not Included");
xlsx.writeFile(wb, "Engineering-Internships-Winter2026-Spring2027.xlsx");
console.log("done");
