import xlsx from "xlsx";

// Distances are straight-line (great-circle) approximations from Boston, MA,
// for quick sorting/reference only — not driving distance.
const rows = [
  {
    Company: "ASM (ASM International)",
    "Role Title": "Manufacturing Engineering Intern",
    Discipline: "Manufacturing Engineering",
    Season: "Spring 2027 (Jan/Feb–Apr/May)",
    Location: "Greater Phoenix, AZ",
    "Distance from Boston, MA (mi, approx.)": 2300,
    Pay: "Not stated on posting",
    "Application Link": "https://www.asm.com/open-vacancies/manufacturing-engineering-intern-spring-2027-4830098101?gh_jid=4830098101",
    "Link Verified": "Yes — fetched directly, page live, Apply button present",
    Notes: "12 weeks, full-time, on-site. Enrolled full-time student required.",
  },
  {
    Company: "ASM (ASM International)",
    "Role Title": "Mechanical Engineering Intern",
    Discipline: "Mechanical Engineering",
    Season: "Spring 2027 (Jan/Feb–Apr/May)",
    Location: "Greater Phoenix, AZ",
    "Distance from Boston, MA (mi, approx.)": 2300,
    Pay: "Not stated on posting",
    "Application Link": "https://www.asm.com/open-vacancies/mechanical-engineering-intern-spring-2027-4830929101?gh_jid=4830929101",
    "Link Verified": "Yes — fetched directly, page live, Apply button present",
    Notes: "12 weeks, full-time, on-site. Enrolled full-time student required.",
  },
  {
    Company: "Varda Space Industries",
    "Role Title": "Manufacturing Engineering Internship",
    Discipline: "Manufacturing Engineering",
    Season: "Spring 2027 (Jan–May)",
    Location: "El Segundo, CA",
    "Distance from Boston, MA (mi, approx.)": 2600,
    Pay: "Not stated on posting",
    "Application Link": "https://job-boards.greenhouse.io/vardaspace/jobs/7824767003",
    "Link Verified": "Yes — fetched directly, page live, Apply button present",
    Notes: "Full-time, on-site. Must be enrolled undergrad/grad.",
  },
  {
    Company: "Formlabs",
    "Role Title": "Mechanical Engineering Intern",
    Discipline: "Mechanical Engineering",
    Season: "Winter/Spring 2027 (Jan–Apr)",
    Location: "Somerville, MA",
    "Distance from Boston, MA (mi, approx.)": 3,
    Pay: "Not stated on posting",
    "Application Link": "https://careers.formlabs.com/job/8130829/apply/?gh_jid=8130829&gh_src=lrhd6k1",
    "Link Verified": "Yes — fetched directly, page live",
    Notes: "Right in the Boston metro. Portfolio of prior engineering work requested.",
  },
  {
    Company: "Blue Origin",
    "Role Title": "Spring 2027 Aerospace Systems Engineering Intern – Graduate",
    Discipline: "Aerospace / Systems Engineering",
    Season: "Spring 2027 (Jan–Apr, ~15 wks)",
    Location: "Greater Seattle Area, WA",
    "Distance from Boston, MA (mi, approx.)": 2490,
    Pay: "Not stated on posting",
    "Application Link": "https://blueorigin.wd5.myworkdayjobs.com/BlueOrigin/job/Greater-Seattle-Area/Spring-2027-Aerospace-Systems-Engineering-Intern---Graduate_R66202/apply",
    "Link Verified": "Partial — official Blue Origin/Workday domain, title confirms season via direct search, but the page is JS-rendered and blocked automated fetch (403/empty). Open a browser to confirm before applying.",
    Notes: "US citizen/national/permanent resident required (ITAR).",
  },
  {
    Company: "Blue Origin",
    "Role Title": "Spring 2027 Aerospace Systems Engineering Internship – Undergraduate",
    Discipline: "Aerospace / Systems Engineering",
    Season: "Spring 2027 (Jan–Apr, ~15 wks)",
    Location: "Greater Seattle Area, WA",
    "Distance from Boston, MA (mi, approx.)": 2490,
    Pay: "Not stated on posting",
    "Application Link": "https://blueorigin.wd5.myworkdayjobs.com/BlueOrigin/job/Greater-Seattle-Area/Spring-2027-Aerospace-Systems-Engineering-Internship----Undergraduate_R66207/apply",
    "Link Verified": "Partial — same as above (Workday page blocked automated fetch). Verify live in-browser before applying.",
    Notes: "US citizen/national/permanent resident required (ITAR). Sophomore standing+.",
  },
  {
    Company: "Blue Origin",
    "Role Title": "Spring 2027 Structural & Mechanical Engineering Internship – Undergraduate",
    Discipline: "Structural / Mechanical Engineering",
    Season: "Spring 2027",
    Location: "Not specified on posting",
    "Distance from Boston, MA (mi, approx.)": null,
    Pay: "Not stated on posting",
    "Application Link": "https://blueorigin.wd5.myworkdayjobs.com/en-US/BlueOrigin/job/Spring-2027-Structural---Mechanical-Engineering-Internship---Undergraduate_R66356",
    "Link Verified": "Partial — official Workday domain, blocked automated fetch. Verify live in-browser before applying.",
    Notes: "US citizen/national/permanent resident required (ITAR).",
  },
  {
    Company: "Blue Origin",
    "Role Title": "Spring 2027 Structural & Mechanical Systems Engineering Internship – Graduate",
    Discipline: "Structural / Mechanical Systems Engineering",
    Season: "Spring 2027 (~15 wks)",
    Location: "Los Angeles, CA",
    "Distance from Boston, MA (mi, approx.)": 2600,
    Pay: "Not stated on posting",
    "Application Link": "https://www.ziprecruiter.com/c/Blue-Origin/Job/Spring-2027-Structural-&-Mechanical-Systems-Engineering-Internship-Graduate/-in-Los-Angeles,CA?jid=67aec7854122d860",
    "Link Verified": "Partial — this is a ZipRecruiter mirror of the Blue Origin listing (couldn't locate the direct Workday URL). Confirm on blueorigin.com/careers before applying.",
    Notes: "Grad student, US citizen/national/permanent resident required (ITAR).",
  },
  {
    Company: "Blue Origin",
    "Role Title": "Spring 2027 Engineering Intern – Undergraduate",
    Discipline: "General Engineering (unspecified sub-discipline)",
    Season: "Spring 2027",
    Location: "Not specified on posting",
    "Distance from Boston, MA (mi, approx.)": null,
    Pay: "Not stated on posting",
    "Application Link": "https://blueorigin.wd5.myworkdayjobs.com/en-US/BlueOrigin/job/Spring-2027--Engineering-Intern---Undergraduate_R69064",
    "Link Verified": "Partial — official Workday domain, blocked automated fetch. Verify live in-browser before applying.",
    Notes: "US citizen/national/permanent resident required (ITAR).",
  },
  {
    Company: "Tesla",
    "Role Title": "Internship, Manufacturing Engineering, Optimus",
    Discipline: "Manufacturing Engineering",
    Season: "Winter/Spring 2027 (Jan–May)",
    Location: "Fremont, CA",
    "Distance from Boston, MA (mi, approx.)": 2700,
    Pay: "$20–$50/hr (Tesla's general posted internship pay band; not role-specific)",
    "Application Link": "https://www.tesla.com/careers/search/job/internship-manufacturing-engineering-optimus-winter-spring-2027-279034",
    "Link Verified": "Partial — official tesla.com domain, blocked automated fetch (403, bot protection). Verify live in-browser before applying.",
    Notes: "Min. 12 weeks, full-time, on-site.",
  },
  {
    Company: "Tesla",
    "Role Title": "Internship, Industrial Engineer, Manufacturing",
    Discipline: "Industrial Engineering",
    Season: "Winter/Spring 2027 (Jan–May)",
    Location: "Fremont, CA",
    "Distance from Boston, MA (mi, approx.)": 2700,
    Pay: "$20–$50/hr (Tesla's general posted internship pay band; not role-specific)",
    "Application Link": "https://www.tesla.com/careers/job/246725",
    "Link Verified": "Partial — official tesla.com domain, blocked automated fetch (403, bot protection). Verify live in-browser before applying.",
    Notes: "Min. 12 weeks, full-time, on-site.",
  },
  {
    Company: "Hendrick Motorsports",
    "Role Title": "Design Engineering Intern",
    Discipline: "Mechanical / Automotive Design Engineering",
    Season: "Spring/Summer 2027 (6–9 month assignment starting spring)",
    Location: "Charlotte, NC",
    "Distance from Boston, MA (mi, approx.)": 845,
    Pay: "Not stated on posting",
    "Application Link": "https://hendrick.wd5.myworkdayjobs.com/en-US/HMSCareers/job/Design-Engineering-Intern--Spring-Summer-2027-_R-80377",
    "Link Verified": "Partial — official Workday domain, blocked automated fetch. Verify live in-browser before applying.",
    Notes: "NASCAR team — structural/CAD design internship. Min GPA 2.8, 30+ semester hrs completed.",
  },
  {
    Company: "General Dynamics Mission Systems",
    "Role Title": "Infrastructure Engineer Co-op",
    Discipline: "Systems / Infrastructure Engineering",
    Season: "Fall 2026 or Spring 2027",
    Location: "Pittsfield, MA",
    "Distance from Boston, MA (mi, approx.)": 135,
    Pay: "Not stated on posting",
    "Application Link": "https://www.gd.com/careers/infrastructure-engineer-co-op-fall-2026-or-spring-2027-pittsfield-ma-us-2026-72403-gdms-opportunity",
    "Link Verified": "Partial — official gd.com domain, blocked automated fetch (403). Verify live in-browser before applying.",
    Notes: "Closest option to Boston besides Formlabs. Likely requires US citizenship (ITAR/clearance).",
  },
  {
    Company: "Boeing (South Carolina)",
    "Role Title": "2026 Specialty Program – BSC Co-op – Engineering Internship Program (Materials & Process Eng, Industrial Eng)",
    Discipline: "Materials/Process Engineering, Industrial Engineering",
    Season: "Fall 2026–Spring 2027 (6-month co-op)",
    Location: "North Charleston, SC (Boeing SC site)",
    "Distance from Boston, MA (mi, approx.)": 850,
    Pay: "Not stated on posting",
    "Application Link": "https://boeing.wd1.myworkdayjobs.com/en-US/INTERN/job/XMLNAME-2026-Specialty-Program---BSC-Co-op---Engineering-Internship-Program_JR2026491626",
    "Link Verified": "Partial — official Boeing/Workday domain, title/search snippet confirms Fall 2026–Spring 2027 span, but page is JS-rendered and blocked automated fetch. Verify live in-browser before applying.",
    Notes: "6-month co-op spanning into Spring 2027.",
  },
  {
    Company: "Boeing",
    "Role Title": "Drexel Internship Fall Co-op 2026 – Engineering (Software, Industrial, Manufacturing, Reliability/Maintainability, Systems, Mechanical Systems, Structures, Wire Install/Design)",
    Discipline: "Systems / Mechanical Systems / Structures / Manufacturing Engineering",
    Season: "Fall 2026–Spring 2027 (6-month co-op)",
    Location: "Not specified on posting (Drexel University co-op partnership — site varies by team)",
    "Distance from Boston, MA (mi, approx.)": null,
    Pay: "Not stated on posting",
    "Application Link": "https://boeing.wd1.myworkdayjobs.com/en-US/INTERN/job/Drexel-Internship-Fall-Co-op-2026---Engineering_JR2026515142",
    "Link Verified": "Partial — official Boeing/Workday domain, title/search snippet confirms Fall 2026–Spring 2027 span, but page is JS-rendered and blocked automated fetch. Verify live in-browser before applying.",
    Notes: "Restricted to Drexel University co-op program students — check eligibility before applying.",
  },
  {
    Company: "John Deere",
    "Role Title": "Part-Time Student – Factory Engineering",
    Discipline: "Manufacturing / Factory Engineering",
    Season: "Year-round part-time during school year (covers Winter 2026 & Spring 2027)",
    Location: "East Moline, IL",
    "Distance from Boston, MA (mi, approx.)": 980,
    Pay: "Not stated on posting",
    "Application Link": "https://careers.deere.com/careers/job/137468659226-part-time-student-factory-engineering-east-moline-il-east-moline-illinois-united-states?domain=johndeere.com",
    "Link Verified": "Partial — official careers.deere.com domain, page structure confirmed real but automated fetch couldn't render full listing text. Verify live in-browser before applying.",
    Notes: "16–20 hrs/wk during school year, 30–40 hrs/wk in summer. Requires graduation Dec 2026 or later. CMM/dimensional-analysis work in production environment.",
  },
  {
    Company: "GE Vernova (Nuclear)",
    "Role Title": "Nuclear Engineering Co-Op/Intern",
    Discipline: "Nuclear / Mechanical / Chemical / Electrical / Materials / Controls / Civil-Structural Engineering",
    Season: "Spring 2027",
    Location: "Wilmington, NC",
    "Distance from Boston, MA (mi, approx.)": 720,
    Pay: "$1,000–$2,000/week (varies by degree level)",
    "Application Link": "https://careers.gevernova.com/ge-vernova-nuclear-engineering-co-op-intern-spring-2027/job/R5048552",
    "Link Verified": "Yes — fetched directly, confirmed OPEN, posted Aug 7, 2026 (within freshness window)",
    Notes: "Housing/relocation assistance if 50+ mi from site. Must be work-authorized without sponsorship.",
  },
  {
    Company: "GE Vernova (Nuclear)",
    "Role Title": "Nuclear – Field Services Spring Internship",
    Discipline: "Engineering / Engineering Technology",
    Season: "Spring 2027 (starts January 2027)",
    Location: "Wilmington, NC (up to 70% travel to nuclear plant sites)",
    "Distance from Boston, MA (mi, approx.)": 720,
    Pay: "$1,000–$2,000/week (varies by experience)",
    "Application Link": "https://careers.gevernova.com/ge-vernova-nuclear-field-services-spring-internship-2027/job/R5049161",
    "Link Verified": "Yes — fetched directly, confirmed OPEN, posted Aug 7, 2026 (within freshness window)",
    Notes: "Housing/relocation assistance if 50+ mi from site. Must be work-authorized without sponsorship.",
  },
  {
    Company: "NASA (Pathways Internship Program)",
    "Role Title": "Pathways Internship – various engineering disciplines",
    Discipline: "Mechanical / Systems / Aerospace (varies by center & opening)",
    Season: "Spring 2027 (apply via USAJOBS; deadline Sept 14, 2026)",
    Location: "Varies — multiple NASA centers nationwide",
    "Distance from Boston, MA (mi, approx.)": null,
    Pay: "Federal student stipend scale, varies by degree level (not a fixed rate)",
    "Application Link": "https://www.usajobs.gov/",
    "Link Verified": "Yes — usajobs.gov is the live, official application portal (this is a program, not a single job req — search USAJOBS for open NASA Pathways postings)",
    Notes: "US citizenship required. Cumulative GPA 2.9+ required. Spring 2027 window opens on USAJOBS in fall 2026.",
  },
  // --- Added 2026-09-19 routine run ---
  {
    Company: "MIT Lincoln Laboratory",
    "Role Title": "Microfabrication Industrial Engineering Co-Op (Group 08-35, Microelectronics Laboratory)",
    Discipline: "Industrial Engineering (Systems Eng/Ops Research/Manufacturing Eng/CS also accepted)",
    Season: "Jan–August 2027 (spans Winter 2026/2027 and Spring 2027)",
    Location: "Lexington, MA",
    "Distance from Boston, MA (mi, approx.)": 13,
    Pay: "$24.50–$31.00/hr (2025 technical co-op rate; subject to review for 2027)",
    "Application Link": "https://careers.ll.mit.edu/job/Lexington-Microfab-Industrial-Eng_-Co-Op-Microelectronics-Laboratory-%28Jan-August-2027%29-Group-08-35-MA-02420/1370647300/",
    "Link Verified": "Yes — fetched directly, active Apply link, no closed/expired banner. Posted Aug 26, 2026.",
    Notes: "Requires US citizenship + eligibility for Secret-level DoD clearance. Sibling req 'Microfabrication Engineering Co-Op' (same Jan–Aug 2027 window, Group 08-35) also exists but wasn't separately fetched.",
  },
  {
    Company: "Draper Laboratory",
    "Role Title": "Systems Engineering Co-Op (Spring 2027)",
    Discipline: "Systems Design Engineering",
    Season: "Spring 2027",
    Location: "Cambridge, MA",
    "Distance from Boston, MA (mi, approx.)": 3,
    Pay: "Not stated on posting",
    "Application Link": "https://draper.wd5.myworkdayjobs.com/Draper_Careers/job/Cambridge-MA/Systems-Engineering-Co-Op--Spring-2027-_JR002882",
    "Link Verified": "Partial — confirmed live via Draper's own job-listings page (draper.com/careers), posted ~1 week ago (~Sept 12, 2026). The Workday req page itself returned blank to automated fetch (JS-rendered) — verify live in-browser before applying.",
    Notes: "Found via Draper's first-party listings page, not an aggregator.",
  },
  {
    Company: "Draper Laboratory",
    "Role Title": "Electro-Mechanical Instrument Co-op (Spring 2027)",
    Discipline: "Hardware / Mechanical Engineering",
    Season: "Spring 2027",
    Location: "Cambridge, MA",
    "Distance from Boston, MA (mi, approx.)": 3,
    Pay: "Not stated on posting",
    "Application Link": "https://draper.wd5.myworkdayjobs.com/Draper_Careers/job/Cambridge-MA/Electro-Mechanical-Instrument-Co-op--Spring-2027-_JR002883-1",
    "Link Verified": "Partial — confirmed live via Draper's own job-listings page (draper.com/careers), posted ~2 weeks ago (~Sept 5, 2026). Workday req page blocked automated fetch — verify live in-browser before applying.",
    Notes: "Found via Draper's first-party listings page, not an aggregator.",
  },
  {
    Company: "Amazon Robotics",
    "Role Title": "Industrial Development Engineer Intern/Co-op, ROBOTICS – 2027",
    Discipline: "Industrial Engineering / Robotics Manufacturing & Technical Operations",
    Season: "2027 (single req covers summer intern, spring co-op, and fall co-op placement — Spring 2027 placement is NOT guaranteed)",
    Location: "Westborough, MA (also Arlington, VA and North Reading, MA)",
    "Distance from Boston, MA (mi, approx.)": 35,
    Pay: "$82,450/year (Amazon standard pay-transparency disclosure for this req)",
    "Application Link": "https://www.amazon.jobs/en/jobs/10536817/industrial-development-engineer-intern-co-op-robotics-2027",
    "Link Verified": "Yes — fetched directly, page loaded fully, role open. UPDATE (2026-09-20): posting text now explicitly reads 'Robotics Industrial Engineer 2027 summer intern, spring co-op, and fall co-op roles' — confirms Spring 2027 co-op is one of the terms this req covers (previously ambiguous).",
    Notes: "Requires graduation between Dec 2026–Aug 2027. Prior req IDs for this role (e.g. 3088739, the 2026-cycle version) are confirmed dead (404).",
  },
  // --- Added 2026-09-20 routine run ---
  {
    Company: "Formlabs",
    "Role Title": "Mechanical Engineering Intern (Winter/Spring 2027)",
    Discipline: "Mechanical / Hardware Engineering",
    Season: "Winter/Spring 2027 (January–April)",
    Location: "Somerville, MA",
    "Distance from Boston, MA (mi, approx.)": 3,
    Pay: "$1,575–$1,950/week (salaried, full-time)",
    "Application Link": "https://careers.formlabs.com/job/8130829/apply/?gh_jid=8130829",
    "Link Verified": "Yes — fetched directly, page live, season/location/pay confirmed in posting text.",
    Notes: "Boston metro. Portfolio of prior engineering work required — application not considered without one.",
  },
  {
    Company: "Formlabs",
    "Role Title": "Hardware Systems Integration Intern (Winter/Spring 2027)",
    Discipline: "Hardware / Electro-Mechanical Engineering",
    Season: "Winter/Spring 2027 (January–April)",
    Location: "Somerville, MA",
    "Distance from Boston, MA (mi, approx.)": 3,
    Pay: "Not stated on posting",
    "Application Link": "https://careers.formlabs.com/job/8172004/apply/?gh_jid=8172004",
    "Link Verified": "Yes — fetched directly, page live, title/season/location confirmed in posting text.",
    Notes: "Boston metro. Portfolio of prior engineering work required.",
  },
  {
    Company: "Eaton",
    "Role Title": "ETO Engineering Co-op",
    Discipline: "Mechanical, Industrial, or Electrical Engineering",
    Season: "Fall 2026 or Spring 2027 (posting states either start date is acceptable)",
    Location: "Syracuse, NY",
    "Distance from Boston, MA (mi, approx.)": 260,
    Pay: "$24.92/hr",
    "Application Link": "https://eaton.eightfold.ai/careers/job/687236797540",
    "Link Verified": "Yes — verified via Eaton's own public Eightfold job-board API directly (the rendered page is JS-heavy); record shows isPrivate: false (publicly listed/active), created 2026-05-21, last updated 2026-08-12.",
    Notes: "Min GPA 2.8. No visa sponsorship (no CPT/OPT/H-1B support). Must live within ~50 mi of Syracuse, NY — no relocation assistance.",
  },
  {
    Company: "Reframe Systems",
    "Role Title": "Mechanical Engineer (Spring 2027 Co-op)",
    Discipline: "Mechanical Engineering (CAD, welding, machining, fixturing/workcell design)",
    Season: "Spring 2027",
    Location: "Andover, MA (HQ) / FAB1 microfactory, Billerica, MA",
    "Distance from Boston, MA (mi, approx.)": 23,
    Pay: "Not stated on posting",
    "Application Link": "https://jobs.ashbyhq.com/reframesystems/f5275832-8373-4971-b5f6-6aaececcb061",
    "Link Verified": "Yes — verified via Reframe Systems' own public Ashby job-board API directly; record shows isListed: true, publishedAt 2026-08-05, exact worksite address (30 Lowell Junction Rd, Andover MA).",
    Notes: "Small modular-construction/robotics-manufacturing startup, Boston metro (Andover/Billerica). Shop-based role — CAD, welding, machining, fixturing.",
  },
  {
    Company: "General Dynamics Electric Boat",
    "Role Title": "2027 Spring Engineering CO-OP Trainee",
    Discipline: "Mechanical / Structural / Aerospace-Aeronautical / Systems / Naval Architecture / Industrial / Electromechanical / Robotics Engineering (multi-discipline req)",
    Season: "Spring of 2027 (per listing summary)",
    Location: "Groton, CT (co-ops also placed in New London/North Stonington CT, North Kingstown/Newport RI)",
    "Distance from Boston, MA (mi, approx.)": 90,
    Pay: "Not stated on posting",
    "Application Link": "https://jobs.buildsubmarines.com/job/601496955",
    "Link Verified": "Partial — found via GD Electric Boat's own dedicated recruiting site (jobs.buildsubmarines.com) with a specific req ID, mirroring the pattern of GD's known 2026 cycle req. The page itself is behind a Cloudflare bot-check wall — blocked on WebFetch, curl w/ browser UA, and a reader-proxy fetch, all returning a security-verification/CAPTCHA screen. Could not independently confirm live/open status or the exact discipline breakdown. Verify live in-browser before applying.",
    Notes: "Was flagged 'worth re-checking' in the prior run; upgraded from 'no verifiable link' to 'specific req ID found, still blocked'.",
  },
  {
    Company: "Anduril Industries",
    "Role Title": "Winter 2027 Mechanical Engineer Co-op",
    Discipline: "Mechanical Engineering",
    Season: "Winter 2027 (16–24 wks, effectively Jan–Aug 2027 — same calendar window other employers call 'Spring 2027')",
    Location: "Quincy, MA",
    "Distance from Boston, MA (mi, approx.)": 8,
    Pay: "$34–$50/hr",
    "Application Link": "https://job-boards.greenhouse.io/andurilindustries/jobs/5236601007",
    "Link Verified": "Yes — fetched directly on Greenhouse, Apply button live.",
    Notes: "Boston metro (Quincy). Corrects an earlier 'checked' entry for Anduril that only found Summer 2027 postings — this Winter 2027 cohort is a separate, later-posted cycle.",
  },
  {
    Company: "Anduril Industries",
    "Role Title": "Winter 2027 Systems Engineer Co-op",
    Discipline: "Systems Engineering",
    Season: "Winter 2027 (effectively Jan–Aug 2027)",
    Location: "Quincy, MA",
    "Distance from Boston, MA (mi, approx.)": 8,
    Pay: "$40–$55/hr",
    "Application Link": "https://job-boards.greenhouse.io/andurilindustries/jobs/5236599007",
    "Link Verified": "Yes — fetched directly on Greenhouse, Apply button live.",
    Notes: "Boston metro (Quincy). Same cohort/site as the Mechanical Engineer Co-op above.",
  },
  {
    Company: "Rivian",
    "Role Title": "Engineering Intern – Manufacturing Engineering (Spring 2027 Co-Op)",
    Discipline: "Manufacturing Engineering",
    Season: "Spring 2027 Co-Op (Jan–Aug 2027)",
    Location: "Normal, IL",
    "Distance from Boston, MA (mi, approx.)": 1000,
    Pay: "~$25–$51/hr per third-party aggregator; not independently confirmed via direct fetch",
    "Application Link": "https://careers.rivian.com/jobs/33784?lang=en-us",
    "Link Verified": "Yes — fetched directly on Rivian's own careers site, title/location/season confirmed.",
    Notes: "",
  },
  {
    Company: "Rivian",
    "Role Title": "Engineering Intern – Design for Reliability (Spring 2027 Co-Op)",
    Discipline: "Mechanical / Design Engineering",
    Season: "Spring 2027 Co-Op (Jan–Aug 2027)",
    Location: "Irvine, CA",
    "Distance from Boston, MA (mi, approx.)": 2600,
    Pay: "~$26–$45/hr per third-party aggregator; not independently confirmed via direct fetch",
    "Application Link": "https://careers.rivian.com/careers-home/jobs/33705?lang=en-us",
    "Link Verified": "Yes — fetched directly on Rivian's own careers site, title/location/season confirmed.",
    Notes: "",
  },
  {
    Company: "SpaceX",
    "Role Title": "Spring 2027 Engineering Internship/Co-op",
    Discipline: "Engineering (multi-discipline req)",
    Season: "Spring 2027 (start Jan or Mar 2027)",
    Location: "Multiple US sites (incl. Bloomfield, CT — see posting for full list)",
    "Distance from Boston, MA (mi, approx.)": null,
    Pay: "$28–$30/hr",
    "Application Link": "https://job-boards.greenhouse.io/spacex/jobs/8616338002",
    "Link Verified": "Yes — fetched directly on Greenhouse, live.",
    Notes: "Corrects an earlier 'checked' entry that grouped SpaceX with companies having 'no Winter 2026/Spring 2027-specific postings' — this Spring 2027 req is a later-posted exception. Likely requires US person status (ITAR) though not explicitly re-confirmed this session.",
  },
  {
    Company: "Rocket Lab",
    "Role Title": "Mechanical Engineering Intern, Spring 2027",
    Discipline: "Mechanical Engineering",
    Season: "Spring 2027 (start Jan/Feb/Mar 2027)",
    Location: "Long Beach, CA",
    "Distance from Boston, MA (mi, approx.)": 2600,
    Pay: "$28/hr",
    "Application Link": "https://job-boards.greenhouse.io/rocketlab/jobs/7985634003",
    "Link Verified": "Yes — fetched directly on Greenhouse, Apply button live.",
    Notes: "Rocket Lab has ~25 more Spring 2027 postings (propulsion, structural, manufacturing, test) across CA/MD/VA/AZ/CO/NM — none in Boston area, not individually logged.",
  },
  {
    Company: "Rocket Lab",
    "Role Title": "Systems Engineering Intern, Spring 2027",
    Discipline: "Systems Engineering",
    Season: "Spring 2027 (start Jan/Feb/Mar 2027)",
    Location: "Long Beach, CA",
    "Distance from Boston, MA (mi, approx.)": 2600,
    Pay: "$28/hr",
    "Application Link": "https://job-boards.greenhouse.io/rocketlab/jobs/7987044003",
    "Link Verified": "Yes — fetched directly on Greenhouse, Apply button live.",
    Notes: "",
  },
  {
    Company: "Collins Aerospace (RTX)",
    "Role Title": "Project Engineering Co-op (Winter/Spring 2027)",
    Discipline: "Systems / Mechanical Engineering",
    Season: "Winter/Spring 2027 (Jan–Jul/Aug 2027, full-time)",
    Location: "Windsor Locks, CT",
    "Distance from Boston, MA (mi, approx.)": 90,
    Pay: "$37,000–$82,000/yr (RTX co-op band)",
    "Application Link": "https://globalhr.wd5.myworkdayjobs.com/REC_RTX_Ext_Gateway/job/US-CT-WINDSOR-LOCKS-B1A--1-Hamilton-Rd--BLDG-1A/Project-Engineering-Co-op--Winter-Spring-2027-_01872478",
    "Link Verified": "Partial — Workday page blocked automated fetch (blank/JS-rendered). Req ID and Sept 14, 2026 posting date confirmed via aggregator mirror only. Verify live in-browser before applying.",
    Notes: "~1.5 hrs from Boston.",
  },
  {
    Company: "Pratt & Whitney (RTX)",
    "Role Title": "Production Support Engineering Co-op (Winter/Spring 2027)",
    Discipline: "Mechanical / Manufacturing / Aerospace Engineering",
    Season: "Winter/Spring 2027 (Jan–Jul/Aug 2027)",
    Location: "Middletown, CT",
    "Distance from Boston, MA (mi, approx.)": 105,
    Pay: "$37,000–$82,000/yr (RTX co-op band)",
    "Application Link": "https://globalhr.wd5.myworkdayjobs.com/REC_RTX_Ext_Gateway/job/US-CT-MIDDLETOWN-220A--Aircraft-Rd--BLDG-220A/Production-Support-Engineering-Co-op--Winter-Spring-2027-_01872654",
    "Link Verified": "Partial — Workday page blocked automated fetch. Req ID and Sept 13, 2026 posting date confirmed via aggregator mirror only. Verify live in-browser before applying.",
    Notes: "~1.5 hrs from Boston.",
  },
  {
    Company: "RTX (Collins Aerospace)",
    "Role Title": "Certification Engineer Co-Op (Winter/Spring 2027, Onsite)",
    Discipline: "Mechanical / Aerospace / Materials Science / Chemical Engineering",
    Season: "Winter/Spring 2027 (Jan–Jul, two semesters)",
    Location: "Winston-Salem, NC",
    "Distance from Boston, MA (mi, approx.)": 700,
    Pay: "$37,000–$82,000/yr (RTX co-op band)",
    "Application Link": "https://globalhr.wd5.myworkdayjobs.com/REC_RTX_Ext_Gateway/job/US-NC-WINSTON-SALEM-190--190-Oak-Plaza-Blvd--BLDG-190/Certification-Engineer-Co-Op--Winter-Spring-2027--Onsite-_01871317-1",
    "Link Verified": "Partial — Workday page blocked automated fetch. Confirmed via aggregator mirror, posting date Sept 16, 2026. Verify live in-browser before applying.",
    Notes: "",
  },
  {
    Company: "RTX (Collins Aerospace)",
    "Role Title": "Mechanical Engineering Co-op (Winter/Spring 2027)",
    Discipline: "Mechanical Engineering",
    Season: "Winter/Spring 2027 (Jan–Jul/Aug 2027)",
    Location: "Cedar Rapids, IA",
    "Distance from Boston, MA (mi, approx.)": 1130,
    Pay: "$37,000–$82,000/yr (RTX co-op band)",
    "Application Link": "https://globalhr.wd5.myworkdayjobs.com/REC_RTX_Ext_Gateway/job/US-IA-CEDAR-RAPIDS-131--5450-C-Ave-NE--BLDG-131/Mechanical-Engineering-Co-op--Winter-Spring-2027-_01869080",
    "Link Verified": "Partial — Workday page blocked automated fetch. Confirmed via aggregator mirror, posting date Sept 15, 2026. Verify live in-browser before applying.",
    Notes: "",
  },
  {
    Company: "RTX (Collins Aerospace)",
    "Role Title": "Structural Engineering Co-op (Winter/Spring 2027)",
    Discipline: "Structural Engineering",
    Season: "Winter/Spring 2027 (Jan–Jul/Aug 2027)",
    Location: "Jamestown, ND",
    "Distance from Boston, MA (mi, approx.)": 1500,
    Pay: "$37,000–$82,000/yr (RTX co-op band)",
    "Application Link": "https://globalhr.wd5.myworkdayjobs.com/REC_RTX_Ext_Gateway/job/US-ND-JAMESTOWN-P1--2604-Highway-20-N--PLANT-1/Structural-Engineering-Co-op--Winter-Spring-2027-_01873938",
    "Link Verified": "Partial — Workday page blocked automated fetch. Confirmed via aggregator mirror, posting date Sept 14, 2026. Verify live in-browser before applying.",
    Notes: "",
  },
  {
    Company: "Northrop Grumman",
    "Role Title": "2027 Spring Mechanical Engineering Co-op",
    Discipline: "Mechanical Engineering",
    Season: "Spring/Summer 2027 (Jan–Aug 2027)",
    Location: "Chandler, AZ",
    "Distance from Boston, MA (mi, approx.)": 2300,
    Pay: "Bachelor's $18.50–$33.50/hr; Master's $26.25–$41.50/hr",
    "Application Link": "https://ngc.wd1.myworkdayjobs.com/Northrop_Grumman_External_Site/job/United-States-Arizona-Chandler/XMLNAME-2027-Spring-Mechanical-Engineering-Co-op---Chandler-AZ_R10249939",
    "Link Verified": "Partial — Workday page blocked automated fetch. Confirmed via aggregator mirror only. Verify live in-browser before applying.",
    Notes: "",
  },
  {
    Company: "Boston Dynamics",
    "Role Title": "Mechanical Engineering Co-Op",
    Discipline: "Mechanical Engineering",
    Season: "Spring 2027 (Jan–Aug 2027, per search snippet)",
    Location: "Waltham, MA",
    "Distance from Boston, MA (mi, approx.)": 10,
    Pay: "$30–$45/hr per search snippet; not independently confirmed via direct fetch",
    "Application Link": "https://bostondynamics.wd1.myworkdayjobs.com/Boston_Dynamics/job/Waltham-Office-POST/Mechanical-Engineering-Co-Op_R2476",
    "Link Verified": "Partial — Workday page returned empty content on two direct fetch attempts (JS-rendered/blocked). Season and pay sourced from search snippet only, not independently opened. Verify live in-browser before applying.",
    Notes: "Boston metro (Waltham).",
  },
  {
    Company: "Berkshire Grey",
    "Role Title": "Spring 2027 Hardware Quality Co-op",
    Discipline: "Hardware / Quality Engineering",
    Season: "Spring 2027",
    Location: "Bedford, MA",
    "Distance from Boston, MA (mi, approx.)": 17,
    Pay: "Not stated (aggregator only)",
    "Application Link": "https://berkshiregrey.bamboohr.com/careers/771",
    "Link Verified": "Partial — BambooHR page rendered empty on two direct fetch attempts. Only confirmed via a third-party aggregator (posted ~Sept 1, 2026), not first-hand. Verify live in-browser before applying.",
    Notes: "Boston metro (Bedford).",
  },
  {
    Company: "Emerson",
    "Role Title": "R&D Engineering Co-Op – Spring 2027",
    Discipline: "R&D / Mechanical Engineering",
    Season: "Spring 2027",
    Location: "Cranberry Township, PA",
    "Distance from Boston, MA (mi, approx.)": 570,
    Pay: "Not stated (aggregator only)",
    "Application Link": "https://hdjq.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/26010785",
    "Link Verified": "Partial — Oracle Cloud ATS is JS-rendered, returned empty content on direct fetch. Sourced via aggregator mirror only. Verify live in-browser before applying.",
    Notes: "",
  },
  {
    Company: "Emerson",
    "Role Title": "Project Engineering Co-op – Spring 2027",
    Discipline: "Project / Mechanical Engineering",
    Season: "Spring 2027",
    Location: "Cranberry Township, PA / Blue Bell, PA / Detroit, MI",
    "Distance from Boston, MA (mi, approx.)": 570,
    Pay: "Not stated (aggregator only)",
    "Application Link": "https://hdjq.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/26010587",
    "Link Verified": "Partial — Oracle Cloud ATS is JS-rendered, returned empty content on direct fetch. Sourced via aggregator mirror only. Verify live in-browser before applying.",
    Notes: "",
  },
];

const checked = [
  { Company: "BWX Technologies (Euclid, OH)", "Role(s) Checked": "Materials Engineering Intern/Co-Op; Manufacturing Engineer Intern/Co-Op", Reason: "Both confirmed FILLED when opened directly (checked Aug 21, 2026)" },
  { Company: "Symbotic (Wilmington, MA)", "Role(s) Checked": "Systems Engineer Co-Op; Machine Learning Intern; Hardware Engineer Intern", Reason: "All specific req links 404'd; live careers page currently shows zero intern/co-op postings, only New Grad roles (checked Aug 21, 2026)" },
  { Company: "Amazon Robotics (Westborough, MA)", "Role(s) Checked": "Industrial Engineer Intern/Co-op; Process Engineer Intern/Co-op", Reason: "Specific job IDs found via search returned 404 (expired/removed) when opened directly" },
  { Company: "Cummins (Columbus, IN)", "Role(s) Checked": "Product Engineering; Materials Science & Engineering; Systems Reliability Engineering Co-Op", Reason: "Cummins.jobs is a JS-rendered SPA — could not confirm season or open status via automated fetch; not included without verification" },
  { Company: "Textron Aviation", "Role(s) Checked": "Spring Co-Op – Electronics Modules Engineer", Reason: "Could not confirm which year (2026 vs 2027) the listing covers; careers.textron.com blocked automated verification" },
  { Company: "GD Electric Boat", "Role(s) Checked": "Engineering Co-Op Trainee", Reason: "Only found a 'Spring 2026' cohort posting (already past) — Spring 2027 cycle not yet posted as of search date" },
  { Company: "Tesla / Apple / Google / Meta / Amazon Lab126 / NVIDIA", "Role(s) Checked": "Various hardware/mechanical searches", Reason: "No Winter 2026/Spring 2027-specific postings found for these disciplines (their volume is overwhelmingly Summer 2027); Apple's 'Hardware Undergrad Engineering' reqs appear evergreen with no season stated. NOTE (2026-09-19): SpaceX has since been found to have a genuine Spring 2027 posting — moved to `rows`; removed from this exclusion group." },
  { Company: "GE Aerospace", "Role(s) Checked": "Manufacturing Engineering Co-op Spring 2027 (x2 reqs); Engines Engineering Co-op Spring 2027; Lynn, MA CNC Trainee Co-Op", Reason: "All 4 specific Spring 2027 reqs found via search had already closed ('no longer posted') when opened directly — this employer's Spring cohort appears to cycle very fast. Worth re-checking careers.geaerospace.com periodically for new Spring 2027 reqs." },
  { Company: "RTX / Raytheon / Collins Aerospace / Pratt & Whitney", "Role(s) Checked": "Spring 2027 co-op search on careers.rtx.com", Reason: "careers.rtx.com search endpoint blocked automated fetch (403); found one Raytheon 'Systems Engineer Co-op (Remote)' but it targets a Summer 2026 start, not Winter 2026/Spring 2027 — excluded on season grounds" },
  { Company: "Anduril Industries", "Role(s) Checked": "2027 Mechanical Engineer Intern; 2027 Manufacturing Engineer Intern (Boston, MA location available)", Reason: "Confirmed Summer 2027 only, not Winter/Spring — excluded on season grounds despite the attractive Boston location. UPDATE (2026-09-19): a separate 'Winter 2027' cohort (effectively Jan–Aug 2027) was found live at Quincy, MA — Mechanical and Systems Engineer Co-ops moved to `rows`." },
  { Company: "Anduril Industries", "Role(s) Checked": "Winter 2027 Electrical Engineer Co-op (Quincy, MA)", Reason: "2026-09-19: Confirmed open/live at the same Quincy, MA site as the Mechanical/Systems co-ops added to `rows`, but excluded here — electrical engineering is outside Hamza's target disciplines." },
  { Company: "Draper Laboratory (Cambridge, MA)", "Role(s) Checked": "Current-openings portal (redirects to Workday)", Reason: "Draper's own site confirms co-ops run fall/spring, but the live openings portal is a JS-rendered Workday page that blocked automated fetch — no specific Spring 2027 req could be confirmed. Worth checking manually (this would be a very close Boston option)." },
  { Company: "MIT Lincoln Laboratory (Lexington, MA)", "Role(s) Checked": "careers.ll.mit.edu search", Reason: "Only Summer 2026 reqs found (e.g. Mechanical/Optical Engineering SRP Intern) — no Spring 2027-specific postings live yet as of search date. Also close to Boston if it opens later." },
  { Company: "Lockheed Martin", "Role(s) Checked": "lockheedmartinjobs.com search for 'Spring 2027'", Reason: "Only found Spring 2026 co-ops (already past); direct search-jobs URL 404'd on retry — no confirmed Spring 2027 req found this session" },
  { Company: "GE Aerospace (Lynn, MA)", "Role(s) Checked": "Lynn CNC Trainee Co-Op; Lynn Carpentry Trainee Co-Op; CNC Programmer Co-op Fall 2026; Manufacturing Engineering Co-op Spring 2027; Engines Engineering Co-op Spring 2027 (Computer/Software track)", Reason: "2026-09-19: All previously-known reqs re-checked directly — now return 'no longer posted' or HTTP 410 Gone. One general Engines Eng Co-op (Cincinnati/Lynn) exists on an aggregator but is flagged EXPIRED there; no live company-site URL found. Worth periodic re-checking of careers.geaerospace.com/global/en/lynn." },
  { Company: "Draper Laboratory", "Role(s) Checked": "Sensor Electrical Engineering Co-op (Spring 2027); Optics-Physics Sensor Engineering Co-op (Spring 2027)", Reason: "2026-09-19: Both confirmed live/open on draper.com's own listings page but excluded — electrical/optics engineering discipline, outside Hamza's target list. (Systems Engineering Co-Op and Electro-Mechanical Instrument Co-op from the same posting batch DID qualify and were added to `rows`.)" },
  { Company: "Symbotic (Wilmington, MA)", "Role(s) Checked": "Full careers.symbotic.com/careers/jobs listing + student/grad opportunities page", Reason: "2026-09-19 re-check: still zero internship/co-op postings; only 'Skillbridge' military-transition fellowships found under a co-op search filter, wrong program entirely." },
  { Company: "Amazon Robotics (Westborough, MA)", "Role(s) Checked": "Old job ID 3088739 (2026-cycle Industrial Engineer Intern/Co-op)", Reason: "2026-09-19: confirmed HTTP 404, dead. Superseded by new req 10536817 (2027 cycle), which was added to `rows` with a season caveat." },
  { Company: "BAE Systems (Nashua, NH)", "Role(s) Checked": "Systems Eng Intern III; Software Eng Intern I/III; EE/CE/RF Intern III; Mechanical Engineering Intern III; Industrial Engineering Co-Op (Fall Semester 2026)", Reason: "2026-09-19: All current postings are explicitly Summer 2027 — wrong season. The one Fall 2026 posting from a prior check now returns HTTP 410 Gone." },
  { Company: "Textron Aviation", "Role(s) Checked": "'Spring Co-Op – Electronics Modules Engineer'", Reason: "2026-09-19 re-check: still cannot confirm which year this posting covers — careers.textron.com remains JS-rendered/blocked to automated fetch; only aggregator mirror found is a stale 2024 cache. No other qualifying Spring 2027/Winter 2026 postings found at Textron, Bell, or Textron Systems in target disciplines." },
  { Company: "General Dynamics Electric Boat (Groton, CT)", "Role(s) Checked": "'2027 Spring Engineering Co-Op Trainee'", Reason: "2026-09-19: Search evidence (job-aggregator snapshot, distinct from the already-past Spring 2026 cohort) suggests a new Spring 2027 cycle exists, but both the aggregator page and the official portals (ebcareers.com, careers-gdeb.icims.com) blocked direct fetch — no verifiable specific req link found, so not added to `rows`. Worth checking ebcareers.com/careers-gdeb.icims.com directly in-browser next run." },
  { Company: "Lockheed Martin / Sikorsky (Stratford, CT)", "Role(s) Checked": "lockheedmartinjobs.com legacy links; new careers.lockheedmartin.com search", Reason: "2026-09-19: legacy job-search URLs now 404 (site appears migrated); new careers site's search endpoint also unreachable via fetch. No Spring 2027 co-op/internship located this session." },
  { Company: "L3Harris", "Role(s) Checked": "'Intern, Software Engineer Spring 2027' (Greenville, TX); 'Electrical Engineer Intern B Spring Co-op'", Reason: "2026-09-19: Only software/electrical Spring 2027 co-ops found — discipline mismatch, no mechanical/structural/systems reqs located." },
  { Company: "Leidos", "Role(s) Checked": "Spring 2027 co-op search", Reason: "2026-09-19: Only software/computer engineering co-ops found (Reston VA, Bethesda MD) — discipline mismatch." },
  { Company: "MIT Lincoln Laboratory (Lexington, MA)", "Role(s) Checked": "Rapid Prototyping Aero/Mech Co-Op", Reason: "2026-09-19: Confirmed open via direct fetch, but posting states 'Fall 2026' only with no stated extension into winter/spring — excluded on season grounds. (A separate Microfabrication Industrial Eng Co-Op, Jan–Aug 2027, DID qualify and was added to `rows`.)" },
  { Company: "Boston Dynamics (Waltham, MA)", "Role(s) Checked": "Mechanical Engineering Intern (req R2495)", Reason: "2026-09-19: Season unstated/unclear on this specific req — excluded. (A separate 'Mechanical Engineering Co-Op' req, Spring 2027, DID have a stated season and was added to `rows` as Partial.)" },
  { Company: "Eaton", "Role(s) Checked": "Co-op Design Engineering (Spring 2027), Jackson, MS", Reason: "2026-09-19: A Spring 2027 co-op wave appears to exist generally ($22–28/hr range per search), but the specific link found (fairygodboss listing) now 404s and no working replacement URL could be located — not added without a verifiable link. Worth re-checking." },
  { Company: "Cummins (Columbus, IN)", "Role(s) Checked": "Career board general search", Reason: "2026-09-19 re-check: career board explicitly shows 'No jobs currently found'; next cycle (Summer 2027) not expected to post until ~Dec 2026." },
  { Company: "iRobot / Vicarious Surgical / Desktop Metal / Markforged / Vecna Robotics / Locus Robotics / PTC / Analog Devices", "Role(s) Checked": "Careers pages and Greenhouse boards for Boston-area robotics/hardware companies", Reason: "2026-09-19: No live Winter 2026/Spring 2027 co-op or intern postings found. iRobot: only an already-past Spring 2026 posting. Vicarious Surgical: careers page/Greenhouse errored out. Desktop Metal/Markforged: Greenhouse board has zero internships posted. Vecna: no listings. Locus Robotics: only Summer 2026 and an apparently-expired Fall 2026 posting. PTC: only standard Summer program. Analog Devices: Spring/Fall co-ops are a standing program but no Spring 2027 req posted yet (expected ~Oct/Nov 2026)." },
  { Company: "Caterpillar / John Deere / Honeywell / 3M / GM / Ford / Stellantis / Lucid Motors / Stanley Black & Decker", "Role(s) Checked": "General co-op/intern search, target disciplines", Reason: "2026-09-19: Confirmed postings found are Summer 2027 only, or (Caterpillar) the application window already closed (Aug 14, 2026). No Winter 2026/Spring 2027-specific reqs located." },
  { Company: "Rockwell Automation / Parker Hannifin", "Role(s) Checked": "General co-op/intern search", Reason: "2026-09-19: No specific postings found — only general recruiting-season descriptions." },
  { Company: "Danaher", "Role(s) Checked": "Product Development Engineering Co-op (Jan 2027 start)", Reason: "2026-09-19: Confirmed posting exists but is located in Vancouver, BC, Canada — excluded on location (outside the US), not season." },
  { Company: "Firefly Aerospace / Sierra Space", "Role(s) Checked": "General co-op/intern search", Reason: "2026-09-19: Only Summer 2026/general 'year-round' postings found; Spring 2027 cycle not live yet (Sierra Space's next cycle not expected until ~Sept 2026 onward)." },
  { Company: "MathWorks (Natick, MA)", "Role(s) Checked": "EDG internship listing", Reason: "2026-09-19: Listing mentions 'Spring, Summer, Fall' cohorts generically but carries no year/season tag on the specific req — appears evergreen, could not confirm as Spring 2027." },
  { Company: "CIRTEC Medical", "Role(s) Checked": "General co-op/intern search", Reason: "2026-09-19: Only generic/Summer, California-based postings found — nothing Winter 2026/Spring 2027 or Boston-area." },
  { Company: "Relativity Space", "Role(s) Checked": "'2027 Mechanical/Electrical Engineer Intern' (lists Boston as a possible site)", Reason: "2026-09-19: Appears to be part of the Summer 2027 program (12-week internship, application window opening ~Sept 2026); could not access job-boards.greenhouse.io/rsinternboard directly (404) to confirm season wording — excluded pending clearer evidence." },
  // --- Added 2026-09-20 routine run ---
  { Company: "Textron Aviation", "Role(s) Checked": "'Spring Co-Op – Electronics Modules Engineer'", Reason: "2026-09-20 re-check: no change. careers.textron.com confirmed to be a Nuxt.js SPA (empty shell on direct fetch, API endpoint redirects back to shell). Aggregator mirror (JobzMall) shows a stale 2024 posting for this exact title/location (Wichita, KS) — likely a recycled listing page, not a live 2027 req. Still cannot confirm year." },
  { Company: "RTX Massachusetts sites (Andover / Tewksbury)", "Role(s) Checked": "careers.rtx.com site search for MA-located Winter/Spring 2027 co-ops", Reason: "2026-09-20: No qualifying co-op found — only a Summer 2027 internship (not co-op) and full-time roles at MA sites. All confirmed Winter/Spring 2027 co-op reqs remain at Jamestown ND and Cedar Rapids IA (already in `rows`), none in MA." },
  { Company: "Analog Devices / Sierra Space / Danaher (US) / Caterpillar", "Role(s) Checked": "Quick re-check for newly-opened Spring 2027 cycles", Reason: "2026-09-20: No change — nothing new surfaced; consistent with prior 'not yet posted' finding." },
  { Company: "Olympus (Westborough, MA)", "Role(s) Checked": "Manufacturing Engineering Co-Op", Reason: "2026-09-20: Only directly-openable listing was a Jan–June 2026 cohort, confirmed CLOSED ('no longer accepting applications'). Aggregator text mentions a possible 'Jan–June 2027' version but could not be independently verified (source JS-rendered, API query 404'd) — excluded pending better verification." },
  { Company: "Alloy Enterprises (Burlington, MA)", "Role(s) Checked": "Co-op board (Thermal Design Engineer, Mechanical Engineer)", Reason: "2026-09-20: Only Fall 2026 and Spring 2026 (already past) co-op reqs found; no Spring 2027 posted yet." },
  { Company: "Commonwealth Fusion Systems (Devens, MA)", "Role(s) Checked": "jobs.lever.co/cfsenergy board directly", Reason: "2026-09-20: Zero internship/co-op postings currently listed (full-time reqs only). Previously-found Fall 2026 and Spring 2026 co-op listings are gone from the live board." },
  { Company: "GE Aerospace", "Role(s) Checked": "Engines Engineering Co-op (R5029619), Manufacturing Engineering Co-op (R5030077)", Reason: "2026-09-20 re-check: both confirmed dead ('no longer posted' / HTTP 410). Still no live Spring 2027 co-op found at Lynn or elsewhere — no change from prior run." },
  { Company: "Teradyne (North Reading, MA)", "Role(s) Checked": "Mechanical Engineering Co-op", Reason: "2026-09-20: Only a Spring 2026 (already past) cohort found; no Spring 2027 posted yet." },
  { Company: "Vicor (Andover, MA)", "Role(s) Checked": "Full careers site", Reason: "2026-09-20: No co-op/internship postings found for any season — full-time roles only." },
  { Company: "Hologic (Marlborough, MA)", "Role(s) Checked": "Co-Op, New Product Development Engineering; Software Eng Co-op; Automation Developer Co-op", Reason: "2026-09-20: Only Spring 2026 (already past) postings confirmed; the NPD Engineering co-op page returned HTTP 503 on two attempts — could not confirm season, excluded." },
  { Company: "iRobot (Bedford, MA)", "Role(s) Checked": "Full careers site", Reason: "2026-09-20: No current Spring 2027 postings found — only historical 2022 listings and older closed Workday reqs." },
  { Company: "Vicarious Surgical (Waltham, MA)", "Role(s) Checked": "Full careers site", Reason: "2026-09-20 re-check: no current Spring 2027 postings; most recent was a January 2026 Mechanical Engineering Co-Op (already past)." },
  { Company: "Apptronik / Figure AI / Agility Robotics", "Role(s) Checked": "Mechanical/hardware internship search", Reason: "2026-09-20: No Winter 2026/Spring 2027 mechanical postings found. One apparent lead (Figure AI 'Hardware Reliability Intern') turned out on direct fetch to be titled Summer 2026 and is closed/removed." },
];
const wsChecked = xlsx.utils.json_to_sheet(checked);
wsChecked["!cols"] = [{ wch: 34 }, { wch: 55 }, { wch: 70 }];

const ws = xlsx.utils.json_to_sheet(rows);
ws["!cols"] = [
  { wch: 26 }, // Company
  { wch: 46 }, // Role Title
  { wch: 34 }, // Discipline
  { wch: 26 }, // Season
  { wch: 22 }, // Location
  { wch: 14 }, // Distance
  { wch: 40 }, // Pay
  { wch: 60 }, // Link
  { wch: 55 }, // Link Verified
  { wch: 50 }, // Notes
];

const wb = xlsx.utils.book_new();
xlsx.utils.book_append_sheet(wb, ws, "Winter26-Spring27 Internships");
xlsx.utils.book_append_sheet(wb, wsChecked, "Checked - Not Included");
xlsx.writeFile(wb, "Engineering-Internships-Winter2026-Spring2027.xlsx");
console.log("done");
